### ISSUE TITLE
How about splitting out `stateToMarkdown.js` into it's own open source lib?

### ISSUE THREAD

**Issue by dbryand** [sstur/react-rte#1]
It would be great to get a hardened `stateToMarkdown` and `markdownToState` into the community as a separate library, decoupled from any particular editor. What about open-sourcing those parts separately from react-rte?

**Comment by sstur** [comment]
Sounds like a good move. I'm almost done with markdownToState and I'm writing tests for stateToMarkdown. Will get them split out as soon as it's working. Thanks!

**Comment by cdownard** [comment]
Should merge #12 into this issue. Think you should do the same with HTML.

**Comment by sstur** [comment]
@dbryand: This is now done. I've factored out all the to/from contentState functionality into npm modules: `draft-js-export-markdown`, `draft-js-import-markdown`, `draft-js-export-html`, `draft-js-import-html`.

The documentation is a little sparse, but hopefully that helps. Please reach out if you need any clarification or examples.

**Comment by dbryand** [comment]
Awesome--I'll give it a look this week. Thanks!
