### ISSUE TITLE
Clear on Focus

### ISSUE THREAD

**Issue by nergmada** [sstur/react-rte#106]
When using this, I often initialise the RTE with some default text value that is basically Lorem Ipsum text (placeholder text). 

It would be nice to be able to specify a boolean flag like 'clearOnInitialFocus' that basically causes the editor to clear the placeholder content when it first receives focus.

I could have a look at trying to implement this, but as you said on the Readme we should post an issue first to see if anyone else is working on this. If this is already achievable, then maybe you could point me in the right direction and I could in return help with documentation.

**Comment by sstur** [comment]
Thanks for using React-RTE and thanks for posting your issue.

I think the feature you're describing is already supported by specifying a `placeholder` attribute.

**Comment by sstur** [comment]
Oh, also the clear on focus is also supported since you can provide an `onFocus` prop (function) and the `value`prop is also controlled by you. So this does not need any feature additions. Correct me if I'm wrong tho.
