### ISSUE TITLE
Typing two dashes (--) should replace it with an em-dash (—)

### ISSUE THREAD

**Issue by louh** [sstur/react-rte#116]
This is a common typographic convention but most editors don't implement it. Is there a way to do this in react-rte? I'm also pretty new to the draft.js ecosystem so I'm not sure if it should be a standalone plugin for draft.js (assuming it does not exist already). What is the most appropriate way to add this?

**Comment by sstur** [comment]
Sorry @louh, I'm not sure the best way to implement this in Draft (possibly listen for the onChange event and manually check/modify editor state). I don't have any plans to implement that behavior in React-RTE core, but you could probably do it in userland. Maybe check for some suggestions in the [Draft Slack Group](https://draftjs.herokuapp.com/)

**Comment by GromNaN** [comment]
The event `handleBeforeInput` can be used.

> At Facebook, we also use this to convert typed ASCII quotes into "smart" quotes, and to convert typed emoticons into images.

https://draftjs.org/docs/api-reference-editor.html#handlebeforeinput
