### ISSUE TITLE
Move Importer/Exporter into own installable module

### ISSUE THREAD

**Issue by cdownard** [sstur/react-rte#12]
Howdy!

I'm reading your repo since I'm running into the storage conundrum where I have services that need to consume what draft has produced. Originally I thought about just storing the JSON object representation of it and then pulling that back out but some of these services don't want to have a conversion step for working with the data.

Consequently, I've been looking at deserializing/serializing it and started writing a basic importer exporter. Which is when I stumbled upon how yours is working. Honestly, I'd just use this component but we need to be able to make ours a little more flexible and support lots of different entities for mentions, tagging, etc.

I really like how your stateFromHTML/element works. I was thinking this almost makes sense to pull outside of rte since it's not rte specific and it could be expanded to support plenty of other types by the community. For instance, xml. Some of your TODOs already mention moving pieces into their own modules, but I'm assuming that's referring to modules inside this repo.

Any thoughts on making a separate dependency for that? I'd be happy to volunteer time to working on it as your approach is the best I've seen in looking around the last couple of days. Someone else had started a repo called DraftExporter but yours is far more robust.

Thanks for your time!

**Comment by sstur** [comment]
Hi @cdownard. You are not the first one to request this, so in fact that's exactly what I've done. Just a few hours before you opened this issue, I published `draft-js-export-html` which is a direct export of `stateFromHTML` from this project. I hope it can help you in your project. Please feel free to contribute.

Also, I'm working with the author of `draft-js-exporter` so that one will use this exporter too.

Thanks!

**Comment by cdownard** [comment]
That's awesome. Are you planning to do the state from html piece as well as
perhaps an import? Happy to help wherever you would like. Think the only
thing I need to do is set up flow.

On Friday, March 11, 2016, Simon Sturmer <notifications@github.com> wrote:

> Hi @cdownard <https://github.com/cdownard>. You are not the first one to
> request this, so in fact that's exactly what I've done. Just a few hours
> before you opened this issue, I published draft-js-export-html which is a
> direct export of stateFromHTML from this project. I hope it can help you
> in your project. Please feel free to contribute.
>
> Also, I'm working with the author of draft-js-exporter so that one will
> use this exporter too.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sstur/react-rte/issues/12#issuecomment-195592107>.
>


-- 
Sent from my iPhone

**Comment by sstur** [comment]
Yes, I've just published the state from html piece on npm as `draft-js-import-html`.

Hope that helps!

**Comment by cdownard** [comment]
You're awesome. 👍

On Friday, March 11, 2016, Simon Sturmer <notifications@github.com> wrote:

> Yes, I've just published the state from html piece on npm as
> draft-js-import-html.
>
> Hope that helps!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sstur/react-rte/issues/12#issuecomment-195651648>.
>


-- 
Sent from my iPhone
