### ISSUE TITLE
Beginning with release 0.7.0 markdown links are lost

### ISSUE THREAD

**Issue by adinardi** [sstur/react-rte#121]
Between release 0.6.0 and 0.7.0 setting the value to markdown with links in it fails to render the links. Upon editing the content the new value of the editor has removed the links from the document.

I can reproduce on the https://react-rte.org/demo page by pasting 

`test [google](google.com) test`

into the editor value field after switching to markdown mode. The link isn't rendered.

![2016-10-28 at 2 55 pm](https://cloud.githubusercontent.com/assets/41189/19823636/8c98ad02-9d1e-11e6-8f94-98a3e2098470.png)

**Comment by sstur** [comment]
Thanks for reporting this! I'll get a fix out ASAP

**Comment by maiers** [comment]
I'd like to help close this issue. Anything I could do?

**Comment by kedius** [comment]
Can you add this fix to release version?

**Comment by maiers** [comment]
Hi Simon / @sstur

could we have the pull request merged anytime soon? Or is there any reason this will not work for you? I really like react-rte, but with images and links broken it's a pain in the ass to remember to patch them manually on each build.

Greetings,
Sebastian

**Comment by tcosentino** [comment]
Hi @maiers could you give me a little guidance on using the fix merged into themaven-net's fork.. 

I've got these dependencies added:

```
    "draft-js": "0.9.1",
    "draft-js-import-markdown": "git+https://github.com/themaven-net/draft-js-import-markdown.git#9d0bf5c",
```

And then have this to set up my initial value

```
  static createValueFromMd(value) {
    if (!value || !value.length) {
      return RichTextEditor.createEmptyValue();
    }

    console.log(value);
    const editorState = EditorState
      .createWithContent(stateFromMarkdown(value));

    return new EditorValue(editorState, { markdown: value });
  }
```

It still doesn't render links in the editor and I get some errors that seem to be compatibility?

```
react-rte.js?e22c:3612 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (eval at <anonymous> (http://localhost:3000/index.js:10141:1), <anonymous>:3612:44)
    at Object.get (eval at <anonymous> (http://localhost:3000/index.js:10141:1), <anonymous>:3472:40)
    at EditorToolbar.value (eval at <anonymous> (http://localhost:3000/index.js:10141:1), <anonymous>:14208:64)
    at EditorToolbar.value (eval at <anonymous> (http://localhost:3000/index.js:10141:1), <anonymous>:14119:113)
    at eval (eval at <anonymous> (http://localhost:3000/index.js:10141:1), <anonymous>:14052:39)
    at Array.map (native)
    at EditorToolbar.value (eval at <anonymous> (http://localhost:3000/index.js:10141:1), <anonymous>:14043:119)
    at eval (eval at <anonymous> (http://localhost:3000/index.js:8730:1), <anonymous>:796:21)
    at measureLifeCyclePerf (eval at <anonymous> (http://localhost:3000/index.js:8730:1), <anonymous>:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (eval at <anonymous> (http://localhost:3000/index.js:8730:1), <anonymous>:795:25)
```

Thanks

**Comment by maiers** [comment]
I can only say what I do. And that's using the latest official release from npm and then I manually apply the changes from the patch.

Luckily this project is only build locally once in a while. Else I would probably script it. Not the best solution, and probably not helpful for you but it works for me.

#Sebastian

--
Sent from a mobile device.

**Comment by tcosentino** [comment]
Oh ok that makes sense, thanks! Other than swapping out the `draft-js-import-markdown`, were there any other changes you remember having to make? I'll give that a go later today

**Comment by maiers** [comment]
I did put all changes into my fork. I am still hoping they will be merged eventually.

--
Sent from a mobile device.

**Comment by bherila** [comment]
@maiers can you open a pull request so I can review and merge it? 

Thanks,
Ben

**Comment by tcosentino** [comment]
@bherila I believe this is the underlying PR https://github.com/sstur/draft-js-import-markdown/pull/8

**Comment by tcosentino** [comment]
@bherila any luck on that? Or is there anything preventing it that I could assist with?

**Comment by bherila** [comment]
I have just returned from a short vacation, I need to build new npm pre-release packages and test some things to see where we are at.

**Comment by bherila** [comment]
@maiers @tcosentino I have released new packages to npm today.

**Comment by sstur** [comment]
Thanks @bherila for the new release. I don't think that fixes this issue, but please correct me if I'm wrong. It is possibly related to one of the modules that react-rte depends on, probably `draft-js-import-markdown`. I'll post back if I find a solution.

**Comment by sstur** [comment]
This is fixed in upstream draft-js-import-markdown and we'll do a new release of react-rte with this version updated.

**Comment by tcosentino** [comment]
@sstur sweet, thanks for the update!

**Comment by williamhoos** [comment]
I think this is closed? Thanks.

**Comment by kenware** [comment]
How do I initialize a content on react-rte

**Comment by kenware** [comment]
ie instead of creating an empty value, at first it will create some value
