### ISSUE TITLE
Styling bolded text to be a different font weight

### ISSUE THREAD

**Issue by Slapbox** [sstur/react-rte#123]
Is there a way to do this? I know it's rendered as a <span> with the font-weight property applied to it directly, so it can't be targeted very easily.

I'd like to lower the font weight for bolded text. Is this possible?

**Comment by sstur** [comment]
This is not really specific to React-RTE. This is part of the Draft-JS API, exposed as a `customStyleMap` prop.

See the docs here:
https://facebook.github.io/draft-js/docs/advanced-topics-inline-styles.html#mapping-a-style-string-to-css
