### ISSUE TITLE
[Support] Markdown to HTML - use only convertor

### ISSUE THREAD

**Issue by pionl** [sstur/react-rte#125]
Hi @sstur, I've tried find a way how to use your markdown converter without using `RichTextEditor.createValueFromString` but I couldn't find solution without using EditorValue.

Is there any way how to convert the markdown text to html without using toString and `EditorValue`?

Thank you

**Comment by sstur** [comment]
You can use https://github.com/sstur/draft-js-import-markdown but I don't have complete docs about how to do it.

**Comment by pionl** [comment]
Ok thanks, will try to use it.
