### ISSUE TITLE
Suggested that the toolbar to do more beautiful

### ISSUE THREAD

**Issue by MinJieLiu** [sstur/react-rte#128]
Suggested that the toolbar to do more beautiful

**Comment by yarnball** [comment]
More information helps @MinJieLiu 

Can you be more specific?

I too would like to customize the tool bar a bit- in particular I'd like to "hide" it by default to the user can choose to see it or not (a simple drop-down panel).

**Comment by revolunet** [comment]
you can add className, toolbarClassName, editorClassName to add some custom styling

**Comment by yarnball** [comment]
Where abouts is would you apply the class name? Inside the render of the element itself?

Because that wouldn't allow my to hide just the editable elements- it would hide the entire text box too
