### ISSUE TITLE
Move position of toolbar icons individually

### ISSUE THREAD

**Issue by yarnball** [sstur/react-rte#129]
Hi,

Great repo. 

I'm using the react-rte-image version, and I'd like to move the position of the "add image URL" icon. In its' current position, it is basically unusable on mobile devices.

How is it possible to move the position of individual buttons?

Thanks

**Comment by ZeroCho** [comment]
@yarnball actually, you should have issued this in react-rte-image. I think this can be possible if you make some css change but i have no idea yet

**Comment by sstur** [comment]
Yes, it's now possible to re-arrange the icons in the toolbar (and show/hide them), however, as @ZeroCho mentioned, we don't have the image icon in this project. That is part of `react-rte-image` but we will get it here soon!
