### ISSUE TITLE
How do you create the distribution build?

### ISSUE THREAD

**Issue by tonyhschu** [sstur/react-rte#134]
**TLDR**: The build process doesn't seem to be producing a `dist` folder at all. This prevents `npm link` and `npm link react-rte` from working when trying to develop locally. (See: https://docs.npmjs.com/cli/link)

When running `npm run build-dist` all that Webpack produces is the `demo.js` file in the `assets/dist` folder. The main entry point specified in the `package.json` file (i.e. `dist/react-rte.js`) is no where to be found.

I must be missing something about how one builds the package for reuse. What am I missing?

**Comment by ZeroCho** [comment]
Yes. This is what I experienced too. I found out that in webpack.config.js, the codes which generate dist folder disappeared after @sstur added webpack-dev-server.

**Comment by ZeroCho** [comment]
To fix it temporarily, add this codes in webpack.config.js

```
{
  entry: './src/RichTextEditor.js',
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'react-rte.js',
    libraryTarget: 'commonjs2',
  },
  externals: {
    react: 'react',
    'react-dom': 'react-dom',
  },
  module: {loaders: loaders},
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      },
    }),
    new webpack.optimize.UglifyJsPlugin({
      beautify: true,
      comments: true,
      mangle: false,
      compress: {
        dead_code: true,
      },
    }),
  ],
}
```

**Comment by tonyhschu** [comment]
Thanks! Other than having to add `var webpack = require("webpack")` at the top, this worked.

Now to see if it actually enables me to make `npm link` work...

**Comment by michaeljota** [comment]
Shouldn't this be added again to `webpack.config.js`?

**Comment by bherila** [comment]
This is fixed now
