### ISSUE TITLE
How to set default font

### ISSUE THREAD

**Issue by MarinusDR** [sstur/react-rte#144]
Where can we set the default fontsize?
In which css?

**Comment by surbina** [comment]
I created a css class called `text-editor`. Then I passed it to the RichTextEditor editor component through the `className` prop type,

Then in my stylesheets I added the following css rules:

```
div.text-editor {
  font-family: inherit;
  ...
}
```

That solved the problem for me.

**Comment by KenRambo** [comment]
@surbina I'm running into the same issue and wasn't able to get your suggestion working. It looks like react-rte keeps injecting script tags that override any styles I declare, and the class name appears as ".RichTextEditor__root___2QXK-". Can you share a bit more about your setup?

I am also running an isomorphic app - not sure if that would cause the complications above...

**Comment by charles-mutabazi** [comment]
@KenRambo 
`<RichTextEditor ... className="text-editor"/>`

and create a css class as @surbina showed it. 
It worked for me.

**Comment by KenRambo** [comment]
Thanks @charles-mutabazi! I got it to work. I think the issue was that I wasn't carrying the styling through via div.text-editor.

**Comment by a9udn9u** [comment]
You can set global styles with the built-in [`rootStyle`](https://github.com/sstur/react-rte/blob/8c81622706a5f8856d39497bf33f92a97e9664fc/src/RichTextEditor.js#L65) property.

For example:
```jsx
<RichTextEditor
    rootStyle={{
      fontFamily: 'sans-serif'
    }}
    ... other props ...
/>
```
