### ISSUE TITLE
when the the todos will be done ?All what i want is in todos.

### ISSUE THREAD

**Issue by qazzhoubin** [sstur/react-rte#146]
I constract serveral editors base on draft.js ,only react-rte is similar to my requires.

But... image is not support. i saw the plan in todo.

editing image is my very important require.

so ,i want to konw how long i will wait for it.

**Comment by MarinusDR** [comment]
It had been nice with a kind of timeline if possible.
Most questions/wishes refer to mentions, images and colors.

**Comment by xiongran** [comment]
so do i,waitting for image

**Comment by bherila** [comment]
There is a pending PR that needs some help, after that, Images will be supported.
