### ISSUE TITLE
Seeing console warning "iterable.length has been deprecated"

### ISSUE THREAD

**Issue by pfarnach** [sstur/react-rte#147]
After bringing react-rte into our project following the basic example in the docs, I'm seeing a console warning:

`iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version`

```
import React, { PropTypes } from 'react';
import RichTextEditor from 'react-rte';

const MarkdownEditor = ({ input }) => {
  return (
    <div>
      <RichTextEditor
        value={ input.value }
        onChange={ input.onChange }
      />
    </div>
  );
};

MarkdownEditor.propTypes = {
  input: PropTypes.shape({
    value: PropTypes.object,
    onChange: PropTypes.func
  })
};

export default MarkdownEditor;

```

The warning is coming from line 2843 inside of react-rte.js.  It seems like this is a warning from an older version of Immutable but I'm not sure why it's showing up here.  A [similar issue was referenced](https://github.com/facebook/draft-js/issues/607) in a resolved DraftJs thread.  Any thoughts?

**Comment by bherila** [comment]
I don't think this issue is within react-rte, it appears to be an upstream issue with DraftJS.

**Comment by AdSoNaTuRaL** [comment]
I'm still getting a lot warnings on log of browser and this is breaking the page. It's coming from react-rte. Any solutions @pfarnach?

**Comment by pfarnach** [comment]
It's been 5 years, I have zero recollection of this issue. I can barely remember what I had for dinner yesterday.
