### ISSUE TITLE
Toolbar icons take keyboard focus. 

### ISSUE THREAD

**Issue by jaepage** [sstur/react-rte#149]
Observed: 
- When I tab my cursor into this editor from a previous form field, I'm required to tab the keyboard focus through all the tools before I can reach the editing box. 

Expected: 
- Focus should jump right into the text box. Tools are accessible via keyboard shortcuts. 

If this is intentional, could my expected behavior above be added an options choice in instantiation? 

Thank you.

**Comment by bherila** [comment]
This is done, you can add extra props to prevent focusing.
