### ISSUE TITLE
[ui] Link button should not use <form>

### ISSUE THREAD

**Issue by sstur** [sstur/react-rte#16]
Using a `<form>` in our toolbar can cause invalid nesting when editor is placed into a parent `<form>`.

**Comment by ZeroCho** [comment]
Is there any problem if you change 'form' to 'div' and 'this._onSubmit' to 'this._onClickSubmit(the event handler when the submit button is clicked)'?

**Comment by sstur** [comment]
The only issue I can think of with that approach is the enter key must be manually listened for (a <form> will auto-submit when enter is pressed while focus is on any form element). That's an easy fix. But I kinda wonder if there is any other special behavior that <form> handles for us, I'm thinking in terms of accessibility..

**Comment by sstur** [comment]
A fix for this is now in master.
