### ISSUE TITLE
suggestion: toString('JSON') or toString('RAW')

### ISSUE THREAD

**Issue by cainlevy** [sstur/react-rte#165]
`react-rte` adds HTML and Markdown output options via `toString(format: string)`, but requires going through `convertToRaw(getCurrentContent())` to get the draft.js format. It might be nice to call the draft.js format `JSON` or `RAW` and support it via `toString()` the same as HTML and Markdown.

**Comment by zbrox** [comment]
This is undocumented, but it was in a recent pull request (#126). I'm using it to store state in a db and then restore it if needed. 

```
value.toString('raw');
RichTextEditor.createValueFromString(value, 'raw');
```

**Comment by cainlevy** [comment]
Excellent, thanks for pulling that up.

**Comment by tathagatbanerjee** [comment]
I'm having some trouble with this, can a simple example be put up? I have a contentState in my db in the raw format. Basically, I'm trying to not do the stateToHTML which should not really be necessary?
```
@observable email = {
  editorState: RichTextEditor
    .createValueFromString(
      stateToHTML(
          convertFromRaw(
            getBodyByLibrary(
              this.props.commsStore.librarySelection,
              this.props.commsStore.emailSelection,
            ),
          ),
        ),
      'html',
    ),
};
```

**Comment by zbrox** [comment]
I save the raw state in DB as well for one application. When I pull the DB value I use it like this `RichTextEditor.createValueFromString(valueFromdb, 'raw')`.

**Comment by tathagatbanerjee** [comment]
I don't think this works. When I looked at the code, it seemed like it should be fine, but I am not having much luck with it.

**Comment by zbrox** [comment]
Judging by the output of the console.log content is not a raw object (which should be a string) but parsed JSON. The `createValueFromString` function expects a string that will be parsed to JSON and then converted to an editor state object. The error in the console is from trying to parse not a string but an object.
