### ISSUE TITLE
Using RTE with Redux

### ISSUE THREAD

**Issue by brunoprela** [sstur/react-rte#168]
We are attempting to use `Redux` to store the `value` field of `RTE` in the `Redux` store, instead of having the `parent` component manage it in its own state. As a result we have implemented the required `parent` component methods as follows:

```
_handleChange(value){
        this.props.updateTextValue(value);
    };

```
where the redux action is:
```
export const updateTextValue = (newValue) => {
    return {
        type: ActionTypes.TEXT_EDITOR.UPDATE_TEXT_VALUE,
        payload: {
            value: newValue
        }
    }
};
```
The issue is that when we do not keep the value in the state, any initialization methods for `value` 
yield an error continuously of:
```

react-rte.js?e22c:15431 Uncaught Error: Format not supported: undefined
    at _toString (eval at <anonymous> (bundle.js:4523), <anonymous>:15431:19)
    at EditorValue.value (eval at <anonymous> (bundle.js:4523), <anonymous>:15483:78)
    at b.rep (eval at <anonymous> (bundle.js:1457), <anonymous>:142:64)
    at Object.com.cognitect.transit.impl.writer.marshal (eval at <anonymous> (bundle.js:1463), <anonymous>:2912:129)
    at Object.com.cognitect.transit.impl.writer.emitObjects (eval at <anonymous> (bundle.js:1463), <anonymous>:2755:48)
    at Object.com.cognitect.transit.impl.writer.emitArray (eval at <anonymous> (bundle.js:1463), <anonymous>:2765:44)
    at Object.com.cognitect.transit.impl.writer.marshal (eval at <anonymous> (bundle.js:1463), <anonymous>:2930:50)
    at Object.com.cognitect.transit.impl.writer.emitTaggedMap (eval at <anonymous> (bundle.js:1463), <anonymous>:2892:271)
    at Object.com.cognitect.transit.impl.writer.emitEncoded (eval at <anonymous> (bundle.js:1463), <anonymous>:2909:44)
    at Object.com.cognitect.transit.impl.writer.marshal (eval at <anonymous> (bundle.js:1463), <anonymous>:2934:50)

```

this results no matter if we initialize the store using any of the following:

`    value: RichTextEditor.createEmptyValue(),
`

or 

`    value: RichTextEditor.createValueFromString('', 'html'),
`

or

`    value: null,
` 

(despite choosing to initialize value as `RichTextEditor.createEmptyValue()` from the `parent` component if the value is sent as null as in the last example.)

Is it acceptable to suppress this error before initializing the component? Or does this have some fundamental problem. If it is okay to do this, would you recommend the 'duck-punching' method on your `ReadMe`? If this error is something fundamental, how can we fix it if we are misusing `rte`, or how can rte change to make this work? Aside from brutalizing the console, we see no other effects on the function of our component.

**Comment by brunoprela** [comment]
UPDATE: We solved this problem by setting the initial state of the store as follows and setting the value to a RTE EditorValue in componentWillRecieveProps.

```
// in textEditorReducer.js:
export const initialTextEditorState = Map({
    value: '',
    state: '',
    form: '',
    current_template: '',
    templates_list: List([])
});
```
```
// in textEditor.jsx:

constructor(props) {
        super(props);
        this.state={
            value: RichTextEditor.createEmptyValue()
        };
        this.handleChange = this._handleChange.bind(this);
    }

componentWillReceiveProps(nextProps) {
        this.props.paneActions.textEditor.updateTextValue(this.state.value.toString('html'));
        const newValue = nextProps.paneData.getIn(['text_editor', 'value']);
        this.setState({value: RichTextEditor.createValueFromString(newValue, 'html')});
    }

And our handleChange was as follows:

```
// in textEditor.jsx:
    _handleChange(value){
        this.setState({value});
    };
```

```
We set the component as follows:

```
// in textEditor.jsx:
<RichTextEditor
                            value={this.state.value}
                            onChange={this.handleChange}
                        />
```

We used the componentWillMount and componentWillUnmount functions of the React lifecycle to give us the functionality we wanted so that textEditor components used in different parts of the application would update properly as well and not interfere with each other. However we are still not sure why this works and the other way of doing it does not.

**Comment by slightlyoffbeat** [comment]
I had the same problem. I ended up keeping the local state, but simply writing to the redux store (by dispatching an action). I also used debounce. Seems to be working fine for me. See below.

```
  onChange = (value) => {
    this.setState({ value });
    this.debounceSetRecipeNotes(value);
  };

  debounceSetRecipeNotes = debounce((value) => {
    const { dispatch } = this.props;
    dispatch(setRecipeNotes(value.toString('html')));
  }, 1000);
```
