### ISSUE TITLE
Toolbar as separate library

### ISSUE THREAD

**Issue by cameracker** [sstur/react-rte#173]
Could we get the toolbar as a separate library or exportable resource? The editor itself was a bit too limited but the toolbar completely meets our needs. Feels a bit unfortunate to have to keep reinventing the toolbar wheel :)

**Comment by tathagatbanerjee** [comment]
Can i please second this? The use case is the opposite. I'm happy with the editor, but want to add functionality to the tool bar specific to the use case. A flexible tool bar would be epic.
