### ISSUE TITLE
Copy/paste from google docs ignores new lines

### ISSUE THREAD

**Issue by wesdotcool** [sstur/react-rte#174]
Copy/pasting text from Google Docs mashes all the paragraphs into a single `<p>` tag instead of one `<p>` per paragraph.
You can recreate this by copying this [test google doc](https://docs.google.com/document/d/1Q8_pUT2y5siH0qeWroKGLQpaJjudRPdjMMb0GzY3seE/edit#heading=h.hms58ty1sg2x) into the [demo](https://react-rte.org/demo)

The output I want is
```
<h2>Title</h2>
<p>Hello</p>
<p>World.</p>
```
However the output I get is
```
<h2>Title</h2>
<p>HelloWorld.<br></p>
```
The html the google doc is producing is
```
<meta charset='utf-8'><meta charset="utf-8">
<b style="font-weight:normal;" id="docs-internal-guid-12fb1824-38b7-6888-67ff-20270759aa8d">
  <h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Title</span></h2>
  <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Hello</span></p>
  <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">World.</span></p>
</b>
<br class="Apple-interchange-newline">
```
That html has an `<h2>` and two `<p>` tags, but they don't seem to make it through into the editor.

I've tried using the `handlePastedText` function, but I'm not sure what is going on, or what I should be doing with it. Here's what I've found
```
    handlePastedText(text: string, html: string): boolean {
        const htmlState = stateFromHTML(html);
        const blockMap = htmlState.blockMap;
        debugger;
        const newState = Modifier.replaceWithFragment(this.editorState.getCurrentContent(), this.editorState.getSelection(), blockMap);
        const result = EditorState.push(this.editorState, newState, 'insert-fragment');
        this.onChange(result);
        return true;
    }
```
At the debugger statement `blockMap` looks like this:
```
blockMap.toArray().map((block) => ({ text: block.getText(), type: block.getType() })) #=>
[
  { text: "", type: "unstyled" },
  { text: "Title", type: "header-two" },
  { text: "Hello", type: "unstyled" },
  { text: "World.", type: "unstyled" }
]
```
It looks mostly okay, but there's a blank block at the top. What is going on here? Is this a bug? What is the best way to get the output I want?

**Comment by harisdz** [comment]
Same issue here.

**Comment by sstur** [comment]
Two points about the example listed above (oops, looks like it's from 2017).

First thing to note is that pasting is handled by draft-js internals, not our specific HTML parser. So if you paste that HTML in the textarea on the demo site (below the draft-js editor pane) you'll see that it actually behaves differently (still not perfect, but not run together in the same paragraph).

Next, it seems that Google Docs is emitting invalid HTML, specifically there are block level elements (`h2`, `p`) inside an inline element (`<b>`). That is not really something we have tuned our parser to handle well. I would be curious to see how an HTML5 standard parser interprets that, but none-the-less it's not going to render as you expect.

Sorry I don't have a better answer there.

**Comment by grundmanise** [comment]
Just wanted to add that not only is the HTML invalid, but the CSS is invalid too. The line-height values don’t match what’s set in the editor – for example, `line-height: 1.38` instead of `1.5`.
