### ISSUE TITLE
Doesn't work with isomorphic apps due to "window" reference.

### ISSUE THREAD

**Issue by nuclearspike** [sstur/react-rte#180]
During compilation, I get the following error:
```
node_modules/react-rte/dist/react-rte.js:14791
        "undefined" == typeof options.singleton && (options.singleton = isOldIE()), // By default, add <style> tags to the bottom of <head>.
                                                                        ^
ReferenceError: window is not defined
    at node_modules/react-rte/dist/react-rte.js:14784:36
```

**Comment by joedski** [comment]
Just ran into this, as well.  It's probably due to this. https://github.com/webpack-contrib/style-loader/issues/109

**Comment by flyingbuddha** [comment]
I get this too. Works when I first compile, but when refreshing the page I get the *window is not defined* error.

**Comment by bherila** [comment]
This will be fixed in the next release. See README for updated webpack instructions for required server-side rendering.

**Comment by mehdiraized** [comment]
> This will be fixed in the next release. See README for updated webpack instructions for required server-side rendering.

Which version?

**Comment by klaaz0r** [comment]
@mehdiraized doesn't seem fixed in the latest releases
