### ISSUE TITLE
getSelection of undefined

### ISSUE THREAD

**Issue by AnjaP7** [sstur/react-rte#183]
Hi,

I'm trying to insert the Editor in my application and always get the error 'getSelection of undefined' when I try to select test in the editor.

I tried your example standalone an it works. However, I can't figure out what is different in my application. Do you have any idea?

Thanks
Anja

**Comment by AnjaP7** [comment]
I found the problem. It was related to my babel configuration.

**Comment by marlonpp** [comment]
Can you share the solution?

**Comment by AnjaP7** [comment]
It was pretty simple. I forgot to exclude the mode_modules from babel in the webpack_config.js. I changed it to this:

module : {
    loaders : [
        test: /\.(js|jsx)$/,
        loader: 'babel',
        exclude: /node_modules/,
        query: {
          presets: ['es2015', 'react']
        }
    ]
  }
