### ISSUE TITLE
Resize editor area

### ISSUE THREAD

**Issue by erisnuts** [sstur/react-rte#187]
Is there some way for user to resize editor area? Like parameter "resize" for tag textarea.

**Comment by sstur** [comment]
No. Sorry there isn't any feature for that.

**Comment by jehartzog** [comment]
@erisnuts You can do this with css. This is the code that worked for me as an example:
```
        <RichTextEditor
          value={this.state.value}
          onChange={this.onChange}
          className="new-post-editor"
          autoFocus
        />
```
```
    .new-post-editor {
        min-height: 150px;
    }
```

**Comment by sstur** [comment]
@jehartzog: I understoodd the question differently. I think @erisnuts is asking how the \*user\* can resize it. As in the little draggable corner on a textarea in modern browsers.

**Comment by jehartzog** [comment]
You're correct about what he was asking, and that CSS I provided definitely won't do that, although the RTE does expand as needed to fit user provided content.

**Comment by simranbling** [comment]
Is there an option to add scroll instead of expanding the as the user provides the content?
