### ISSUE TITLE
Including react-rte into my bundle.js increases filesize by 334kb

### ISSUE THREAD

**Issue by strongui** [sstur/react-rte#190]
Is this expected behavior, 300+kb for a WYSIWYG editor? Are there any performance tweaks I can do to get this down?

**Comment by sstur** [comment]
That seems high. It should be about 100k minified, including React and ReactDOM (which presumably you already have in your project so the actual size increase should be less). For comparison TinyMCE (when tested some time ago) adds about 170kb and it has heaps more features and junk.

So I think this might be either a mis-measurement or a product of a built toolchain that is not sub-optimal (such as including lots of copies of certain dependencies) or it could be a regression in our code.

It will take some investigation to find out for sure.

**Comment by mplis** [comment]
[This](http://imgur.com/a/PpbKT) is what I'm seeing when using `webpack-bundle-analyzer`. The `react-rte.js` file that is being included in my bundle is very large. If I dig into `node_modules`, I can confirm that the file is that size, so I don't believe it is a mis-measurement:

```
-> % ll node_modules/react-rte/dist
total 5096
-rw-rw-r--  1 mplis  staff   1.6M Nov  4  2016 demo.js
-rw-rw-r--  1 mplis  staff   899K Nov  4  2016 react-rte.js
```

**Comment by mplis** [comment]
Looking through the history of your webpack config file, I noticed that large sections of the config file were removed in the most [recent commit](https://github.com/sstur/react-rte/commit/237a48618f8788c93c4bbe5cdbca3aff225c5450). Could that be the problem?

**Comment by bherila** [comment]
In the next release, you will be able to include the lib directly in your webpack bundle which will result in a reduced bundle size. In my current testing off master branch, including react-rte now increases bundle size by only around ~230kb.
