### ISSUE TITLE
Graceful support for server side rendering

### ISSUE THREAD

**Issue by iaincollins** [sstur/react-rte#191]
It would be really great if it there was graceful support when using server side rendering for use in universal apps - frankly even if the default behaviour on the server was just to render a textarea where window.* is not present, and upgrade to a rich editor only when run inside the browser rather than on the server.

Currently it bombs when it can't find window.* so can't be included with universal projects where templates might also be rendered on the server.

**Comment by joedski** [comment]
+1 to this.  I've gotten around it for now by creating a `ClientSideOnly` HOC, which literally just doesn't even instantiate whatever it's wrapping until _after_ `componentDidMount`, which means it also incurs another render pass.  Woo.

```js
export default (Component) => (
  // NOTE: in my actual code I also modify `displayName` to be `ClientSideOnly(${Component.displayName})`
  class ClientSideOnly extends PureComponent {
    state = { isMounted: false }

    componentDidMount() {
      // Don't queue another state update until after this current pass is done.
      // Hacks all around!
      Promise.resolve(null).then(() => this.deferredMount());
    }

    deferredMount() {
      this.setState({ isMounted: true });
    }

    render() {
      if (!this.state.isMounted) return null;
      return <Component {...this.props} />;
    }
  }
);
```

**Comment by iaincollins** [comment]
Thanks! This is super helpful suggestion that hadn't occurred to me.

**Comment by bherila** [comment]
Hey @joedski or @iaincollins any chance you can send a PR? I'm working with Simon to hopefully be able to get through the PR and issue backlog and get new packages released that will work for folks like myself who need to use react-rte in an isomorphic rendering environment. Thanks!!

**Comment by joedski** [comment]
@bherila Whatcha thinkin?  Pull out the `style-loader` stuff and have the styles passed in only?  Switch to `css-modules`?  Use JS styles directly?

**Comment by bherila** [comment]
I am thinking that perhaps the node_module for this project should not be a webpack bundle at all, but rather the individual files. Projects that import react-rte would then import some index.js file and thus the .css files would be resolved by whatever loader the consumer desires. 

For example, in one project I'm working on I have the following loader configured in my webpack server.js file: 

```
      {
        test: /\.css$/,
        loaders: [
          'isomorphic-style-loader',
          'css-loader?modules&importLoaders=2&localIdentName=[local]___[hash:base64:5]'
        ]
      }
```

and on webpack client.js file:

```
      {
        test: /\.css$/,
        exclude: path.resolve('./src/app'),
        loaders: [
          'style-loader',
          'css-loader'
        ]
      },
```

and on webpack client prod .js file, I use css-loader to extract all the styles into a static .css file which can be cached on CDN:

```
      {
        test: /\.css$/,
        exclude: path.resolve('./src/app'),
        loader: ExtractTextPlugin.extract({
          fallbackLoader: 'style-loader',
          loader: [
            'css-loader',
          ]
        })
      },
```

Having everything pre-bundled precludes this from working at all.

Would anyone be opposed to changing the package format so it's not pre-webpack'd?

**Comment by joedski** [comment]
Changing it to not-pre-webpacked would be great for us!

**Comment by bherila** [comment]
@joedski Here's something I whipped up and am playing with now

`npm install react-rte@https://ucassets.blob.core.windows.net/test-ben/layout/react-rte-0.12.0.tgz`

**Comment by bherila** [comment]
@joedski it looks like css-loader isn't resolving the .css files that are now in the node_modules, any idea how to do it the "right way"?

**Comment by bherila** [comment]
I got it working!!

**Comment by jamesgallagher432** [comment]
@bherila Sorry to bring up such an old issue, but I am seeing the same issue as you described in your message "SyntaxError: Unexpected token .". Is this a react-rte issue or an issue with Webpack? Here is my config below:
[webpack.config.prod.txt](https://github.com/sstur/react-rte/files/2288859/webpack.config.prod.txt)

**Comment by bherila** [comment]
Sorry @jamesgallagher432 I am not using this library anymore.

**Comment by jamesgallagher432** [comment]
Thanks anyway!
