### ISSUE TITLE
Insert soft newline pressing "Enter" key or just remove extra white space

### ISSUE THREAD

**Issue by detrash08** [sstur/react-rte#193]
Is there a way to add soft newline instead block after pressing enter key? I'd like to avoid the extra white space added with the new paragraph. Looking into the html of text displayed by RTE, I see that every block (paragraph) has an extra margin. Is there a way (not a css ninja way) to remove that margin?

**Comment by sstur** [comment]
Does it work if you press shift+enter?

**Comment by detrash08** [comment]
Yes everything is working as expected. I just want to customize the block appearance removing the extra space between lines. I'm asking if it could be possible without replacing the editor CSS classes

**Comment by sstur** [comment]
> I'm asking if it could be possible without replacing the editor CSS classes

I don't think there is an option for that besides using CSS.

To be clear, you mean the appearance IN the editor, right? Not modifying the output of `draft-js-export-html` right?

**Comment by detrash08** [comment]
I mean the appearance in the editor.
