### ISSUE TITLE
Demo site not working in IE11

### ISSUE THREAD

**Issue by Trecxs** [sstur/react-rte#196]
Demo site is not working in IE11. 

Error in console with demo.js:

> Object doesn't support property or method 'startsWith'

Perhaps not so much a bug to react-rte but more to the site.

**Comment by mvanlonden** [comment]
I think this is an es5 backwards compatibility problem. You can use `react-rte-es5` until this is fixed. Watch this [PR](https://github.com/sstur/react-rte/pull/204). Hope it helps

**Comment by bherila** [comment]
@Trecxs is this solved now that we have #204 merged?

**Comment by Trecxs** [comment]
Just triend it, but same error unfortunaly.

**Comment by bherila** [comment]
Yup startsWith is not supported in IE

![image](https://user-images.githubusercontent.com/1422004/28252101-7e7fba26-6a41-11e7-87df-60ef55538b48.png)

**Comment by bherila** [comment]
I don't think the `startsWith` code is in this repo, can someone pinpoint where it is coming from and file an issue against that, or send a PR that includes the polyfill in the appropriate place

```js
if (!String.prototype.startsWith) {
    String.prototype.startsWith = function(searchString, position){
      return this.substr(position || 0, searchString.length) === searchString;
  };
}
```

Thanks,
Ben
