### ISSUE TITLE
Needs polyfills for IE and phantomjs support 

### ISSUE THREAD

**Issue by mvanlonden** [sstur/react-rte#203]
In order to have full es5 compatibility needed to add polyfills 
- String.prototype.startsWith
- Array.from
- Array.prototype.fill
- Array.prototype.keys
- Array.prototype.findIndex
- Number.isInteger

I included them via polyfill.io and it's working now
`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=String.prototype.startsWith,Array.from,Array.prototype.fill,Array.prototype.keys,Array.prototype.findIndex,Number.isInteger&flags=gated"></script>`

Would be nice if this was covered in the transpiling. Will submit a pr with a revised `.babelrc`

**Comment by bherila** [comment]
I don't think we want to include the polyfills in the transpiling, because not everyone wants to target ES5 and then if the package were ever upgraded to ES6 it would be a breaking change. I will add this to the README however.

**Comment by manojnegiasc** [comment]
Adding pollyfill 
String.prototype.startsWith
Array.from
Array.prototype.fill
Array.prototype.keys
Array.prototype.findIndex
Number.isInteger

Worked. thanks 👍 @mvanlonden
