### ISSUE TITLE
Styles exposed by Draft.global.css affecting other instances of Draft.js

### ISSUE THREAD

**Issue by sgwilym** [sstur/react-rte#210]
I've encountered a problem after trying to use react-rte alongside another editor built in-house with Draft.js. The in-house editor required all of its own styling for blocks, and so we omitted including the default Draft.css, as there's no way to make Draft.js not attach the default class names (eg `.DraftEditor-alignLeft`). 

When we started using react-rte we found some of the layout in our in-house editor stopped working as expected, and it was because Draft.global.css had been included by react-rte.

Would it be possible to scope the styles react-rte relies on so that it doesn't affect other instances of Draft.js, and if so, what would you find the preferable way to approach it? I'm currently using a quick fix solution with a fork of this package that adds a class to the rendered react-rte editor, and edits the class names in Draft.global.css so that it'd only affect descendants of that class.

Thanks for your time!

**Comment by bherila** [comment]
Please see the README for instructions building react-rte into your app directly using webpack. Style loader will generate unique css class names during this process.

> import RichTextEditor from react-rte/lib/RichTextEditor in order to get the un-bundled script which webpack can bundle with your app.
