### ISSUE TITLE
Displaying link from markdown string doesn't work 

### ISSUE THREAD

**Issue by SvetlanaMalakhova** [sstur/react-rte#211]
when I try to set to editor value using markdown string with link - at the editor I don't see link, only simple text (https://screencast.com/t/HOZ0fPUcIblJ). 
let value = RichTextEditor.createValueFromString(this.props.markdown, 'markdown');
and this.props.markdown = `[some text with link](https://www.youtube.com/watch?v=ZoEFTsw1HA0)`
How can I resolve this problem?

**Comment by bgmort** [comment]
This has been reported in #121 and fixed, but not merged yet.

**Comment by bherila** [comment]
@SvetlanaMalakhova can you confirm if this is fixed in the latest build?

Thanks,
Ben

**Comment by SvetlanaMalakhova** [comment]
@bgmort nope :( I still have this problem

**Comment by sstur** [comment]
This has been fixed in react-rte@0.14.0.
