### ISSUE TITLE
Code Block not working as expected

### ISSUE THREAD

**Issue by CharlesIrvineKC** [sstur/react-rte#213]
Inserting a code block isn't working as expected. To illustrate, go to:

1. got to: https://react-rte.org/demo
1. pick "Code Block" from the styles dropdown.
1. try to paste some code into the code block.

For me this results a bunch of paragraph html elements.

See attached screen shot.

![screen shot 2017-06-30 at 5 49 41 pm](https://user-images.githubusercontent.com/657002/27756381-8c1a8efe-5dbc-11e7-95ba-b244ee40b244.png)

**Comment by chiedo** [comment]
It doesn't look like codeblocks are supported. Only inline code

**Comment by mc-funk** [comment]
Can verify that "code blocks" just go line by line and create inline code, which does not seem to be the behavior one would expect for code block since it exists separately from the inline code style button. Seems like instead it should wrap in ```s.
