### ISSUE TITLE
SSR not working - "ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by jooj123** [sstur/react-rte#218]
See: 
https://github.com/sstur/react-rte/pull/217

Seems that `style-loader` stuff is part of build js ?

Im using browserify

**Comment by bherila** [comment]
if you would like to eliminate the window dependency you will need to use your own webpack config with a style loader of your choice and import `'react-rte/lib/RichTextEditor'` as described in https://github.com/sstur/react-rte/commit/0a15bf37a0dd9dbfe01cdbe6844906db4518d08f

The npm packages that solve this are not released yet. Coming in the next release as soon as we fix the build issues.

**Comment by jooj123** [comment]
Ok thanks 
Being forced to use webpack was not ideal in my situation so i had to move back to vanilla `draft-js`

**Comment by hrahimi270** [comment]
Sorry for commenting on a closed issue.
Currently, it's possible to use `react-rte` on a next.js project?
