### ISSUE TITLE
Link and Remove Link Buttons are disabled

### ISSUE THREAD

**Issue by chattes** [sstur/react-rte#224]
Hi,
As you can see in the Demo page as well the Link and remove Link buttons are disabled. How do i fix this?

![image](https://user-images.githubusercontent.com/11190834/28716652-fc068fb4-73bb-11e7-98ba-395f6ee14d1c.png)

**Comment by chattes** [comment]
Please ignore I figured out how to open the links

**Comment by The-Code-Monkey** [comment]
How did you manage to do this as mine are disabled?
