### ISSUE TITLE
Link should be open in a new tab

### ISSUE THREAD

**Issue by NE-SmallTown** [sstur/react-rte#228]
Currently we use `<a href="www.foo.com">link</a>`, but for SPA it won't work well, we need to use `<a href="www.foo.com" target="_blank">link</a>` instead.

**Comment by alekshs** [comment]
If you want all your links to open in new tab, change the value you send to the parent component from:
value.toString('html')
to:
value.toString('html').replace(/<a /g, '<a target="_blank" ')

The good thing is that react-rte parses html special characters, so, you don't have to worry about conflicts between simple text and real anchor tags.

**Comment by NE-SmallTown** [comment]
Thanks for your reply. But I still think we usually use react-rte in a SPA, and as an editor, the user use link to add **external** link rather current website link, so I think change the default behavior would be better.

**Comment by bherila** [comment]
I think that would be the right design choice. Can you send a pull request?

**Comment by NE-SmallTown** [comment]
These days are too busy. Sorry for that I don't have enough time to to pr,  and there are some details need to consider so if you want to help on this I am happy to review :)

**Comment by sstur** [comment]
To be clear, is this on the HTML output?

If so we should open this issue for [draft-js-export-html](https://github.com/sstur/draft-js-utils) which is what react-rte uses to output html.

I'd be open to the option suggested by @tiberiumaxim for a `openExternalLinksInNewTabs` option which would be a super easy PR except that he suggests detecting if the link is same-origin or not and applying different behavior based on that.

**Comment by sstur** [comment]
To be clear, this is already possible now, by specifying an `entityStyleFn` function as per the docs [here](https://github.com/sstur/draft-js-utils/tree/master/packages/draft-js-export-html#entitystylefn).

@alekshs: no need to do string manipulation such as `value.toString('html').replace(/<a /g, '<a target="_blank" ')` since we can specify the function above to process entities during serialization.

**Comment by NE-SmallTown** [comment]
> To be clear, is this on the HTML output?

 Yes.

Thanks for your workaround. But I think `specifying an entityStyleFn` is unnecessary because we are talking about **default** behavior. And "detecting if the link is same-origin or not and applying different behavior based on that" sounds great to me :)

**Comment by williamhoos** [comment]
What does the community think about creating two options for the target=_blank functionality:


1.  When using this gem, a default configuration option to specify whether links will be rendered with or without the new window target?
2. A UI option to change - Have a default configuration option for whether to allow a user to change the setting. The most logical place for this option seems to be a checkbox in the WYSIWYG link button for "open in new window" - if there is this UI option, then a configuration option at the gem level for whether to enable the checkbox and the checkbox default value would be the default value in 1 above.

If acceptable to the project, anyone want to code it or I'll try to find a way to get it done.

**Comment by will-tb** [comment]
Any update to this issue?

**Comment by slavikdenis** [comment]
+1

**Comment by williamhoos** [comment]
Note, I tried to separate this out to a more flushed out specific issue. Would love to have someone take this on.

https://github.com/sstur/react-rte/issues/244

**Comment by sstur** [comment]
Closing in favor of #244
