### ISSUE TITLE
document API with expected properties, usage, etc.

### ISSUE THREAD

**Issue by simpixelated** [sstur/react-rte#23]
Something like:
* https://github.com/theadam/react-inform/blob/master/README.md#api
* https://github.com/christianalfoni/formsy-react/blob/master/API.md

From my limited knowledge, I could get this started with:

### RichTextEditor
Main editor component, with draft-js `<Editor>` and custom toolbar.
#### Properties
* `value`: used to populate the initial content of the editor; if no previous value is available, should be populated with `RichTextEditor.createEmptyValue()`
* `onChange`: function that will be passed the value of the editor whenever it is changed. The value object passed to this function has a `toString` method which accepts a string of either 'html' or 'markdown'

#### Example usage:
```javascript
import RichTextEditor from 'react-rte';

class MyCustomEditor extends Component {

  static propTypes = {
    onChange: PropTypes.func.isRequired
  };

  state = {
    value: RichTextEditor.createEmptyValue()
  }

  handleChange = value => {
    this.setState({ value });
    // send the changes up to the parent component as an HTML string
    this.props.onChange(value.toString('html'));
  };

  render () {
    return (
      <RichTextEditor
        value={this.state.value}
        onChange={this.handleChange}
      />
    );
  }
}
```

**Comment by simpixelated** [comment]
FYI I do mean the react-rte API, not draft-js. I realize a lot of the above are props on draft-js `Editor`. The react-rte API should point to the [Draft.js docs](https://facebook.github.io/draft-js/docs/overview.html#content) when it's just passing props, but highlight any differences or unique properties (like value.toString).

**Comment by sstur** [comment]
This is great stuff. I'll reword a couple minor things and land this in the Readme. Thanks!

**Comment by sstur** [comment]
(I love your use of ES6 class properties. I hope that will be clear to people reading the who don't live on the bleeding edge like us ; )

**Comment by simpixelated** [comment]
Might be worth considering an ES5 example as well; I often see that on other repos.

**Comment by sstur** [comment]
Done. Maybe you can proof read and let me know if it all makes sense..

**Comment by simpixelated** [comment]
Looks great!
