### ISSUE TITLE
did you forget return

### ISSUE THREAD

**Issue by imchenglibin** [sstur/react-rte#231]
in EditorToolbar.js 

_renderCustomControls() {
    let {customControls, editorState} = this.props;
    if (customControls == null) {
      return;
    }
    customControls.map((f) => {
      switch (typeof f) {
        case 'function': {
          return f(
            this._setCustomControlState,
            this._getCustomControlState,
            editorState
          );
        }
        default: {
          return f;
        }
      }
    });
  }

change to 

_renderCustomControls() {
    let {customControls, editorState} = this.props;
    if (customControls == null) {
      return;
    }
    **return** customControls.map((f) => {
      switch (typeof f) {
        case 'function': {
          return f(
            this._setCustomControlState,
            this._getCustomControlState,
            editorState
          );
        }
        default: {
          return f;
        }
      }
    });
  }

**Comment by j-san** [comment]
There is already a PR for that :D https://github.com/sstur/react-rte/pull/227

**Comment by bherila** [comment]
Thanks
