### ISSUE TITLE
Only one instance of babelpoly-fill is allowed

### ISSUE THREAD

**Issue by philswinney** [sstur/react-rte#232]
Hi,
I'm attempting to implement react-rte into a large application that is already using the global babelpoly-fill plugin. When I install and import the RichTextEditor component I get a duplicate instance of babel poly-fill error. Any suggestions on how I can reconfigure the install?

**Comment by philswinney** [comment]
Adding ... the error gets thrown when we attempting to us dynamic page loading via the route module.

**Comment by Shywim** [comment]
I just upgraded my `react-rte` dependency and I also encountered this error. The issue come from [this commit](https://github.com/sstur/react-rte/commit/bb17a735e4a3fa054f361abb610e43b94e22f713), you should not directly use babel-polyfill in your library and just tell users of the library that it may be required (as said [in the babel repository](https://github.com/babel/babel/issues/1019#issuecomment-127705958))

**Comment by sstur** [comment]
Thank you for reporting this. You are correct, libraries shouldn't load polyfills. I'll revert that commit and publish a new version.

**Comment by sstur** [comment]
I've published v0.15. Please let me know if that fixes this issue.

**Comment by Shywim** [comment]
Everything is fine now, here. Thanks for the fast fix! 😃
