### ISSUE TITLE
global is not defined react-rte

### ISSUE THREAD

**Issue by kishorenekkalapudi** [sstur/react-rte#235]
we are using
 import RichTextEditor from "react-rte/lib/RichTextEditor";

we are getting following error on client-side. Can anyone please help us

![screen shot 2017-09-18 at 3 54 39 pm](https://user-images.githubusercontent.com/1307578/30568467-362f966c-9c8a-11e7-8eff-fc0185e4f6b1.png)

**Comment by ishwinder** [comment]
Hey, were you able to get around it ? Facing the same issue here.

**Comment by kishorenekkalapudi** [comment]
Hey, This issue with server side render (isomorphic). try to remove it

**Comment by kishorenekkalapudi** [comment]
The issue is not on the client side
