### ISSUE TITLE
Block Type Dropdown: <option> text is transparent

### ISSUE THREAD

**Issue by amcintyre-cs** [sstur/react-rte#26]
It looks like the text of the `option` elements inside of the Block Type dropdown is set to transparent, which has the affect of making the text invisible (at least in Chrome 49).

**Comment by sstur** [comment]
Really? If so, that's a bug. Can you take a screenshot? I'm on Version 49.0.2623.87 (64-bit). For me it looks like this:

https://www.dropbox.com/s/4v87akwq0ejxqun/Screenshot%202016-04-06%2022.29.57.png?dl=0

**Comment by amcintyre-cs** [comment]
I'm on Windows, so maybe it's a weird Windows thing with the select control? I'm testing a patch for it now.

All of my screenshot software is closing the dropdown whenever I try to capture a screenshot. It's currently driving me nuts. :smile: I'll try to grab one if I can.

**Comment by amcintyre-cs** [comment]
Screenshot from Chrome 49.0.2623.110 m on Windows:
![screenshot](https://cloud.githubusercontent.com/assets/1560925/14323235/b1d140ac-fbed-11e5-978a-f1ab645eef95.png)
