### ISSUE TITLE
react-rte is huge

### ISSUE THREAD

**Issue by moimael** [sstur/react-rte#264]
Hi,

Just had a quick look at our bundle size recently and it seems like react-rte is really huge. It takes around 1MB in our bundle. Any way to make it slimmer ?

Thanks !

![screenshot from 2018-01-30 10-10-00](https://user-images.githubusercontent.com/1479859/35557623-eac74b72-05a5-11e8-9051-a5b722d414fb.png)

**Comment by benjy** [comment]
Can you do a du -chs * inside the folder? Mine is nothing like that size locally, not sure what's going on here, wondering if something is wrong with the package deployed to npm.

**Comment by moimael** [comment]
Sure here it is:
```
4,0K	CHANGELOG.md
2,8M	dist
220K	lib
4,0K	LICENSE
8,0K	package.json
16K	README.md
3,0M	total
```
And inside dist which seems to be the culprit:

```
1,8M	demo.js
1,0M	react-rte.js
2,8M	total
```

So I guess the demo shouldn't be included but since we have tree shaking that's probably not the issue here, react-rte.js is still 1MB.

**Comment by moimael** [comment]
Playing around with babel and webpack conf, I managed to get the size down from 1.04MB to 381KB.

I just removed all options in the webpack uglifyjs plugin (this has the largest impact) and added `module: false` to es2015 preset (this only saves 3KB) so webpack can do it's magic.

**Comment by benjy** [comment]
381KB seems better but still pretty huge, open to suggestions if there is something obvious we can do to reduce size. It would probably require running the size total you are using on this repo itself, to see where our biggest dependencies are?

**Comment by moimael** [comment]
Down to 378KB using `webpack -p` instead of just `webpack`

**Comment by moimael** [comment]
Analysing the bundle, draft-js and immutable are the biggest deps. Also immutable is included twice.

![screenshot from 2018-01-31 12-14-21](https://user-images.githubusercontent.com/1479859/35620114-6055e21a-0680-11e8-9362-a1558040663c.png)

**Comment by benjy** [comment]
That's kind of sad, I don't think we can remove either of those. Not sure why it would be in there twice, one of our dependencies has a different version constraint for immutable to what we have?

**Comment by moimael** [comment]
For immutable we are blocked by draftjs, they are discussing making it a peerDep which would solve the issue, but in the meantime we are stuck...

**Comment by NNSTH** [comment]
I'm facing the same issue, which has not been solved after run: npm update react-rte@latest,
Can you explain how can I get this fix to reduce my bundle size? thanks.
