### ISSUE TITLE
React 16 complains about ref

### ISSUE THREAD

**Issue by vestimir** [sstur/react-rte#282]
I'm getting this error with React 16:

```
Element ref was specified as a string (editor) but no owner was set. You may have multiple copies of React loaded.
```

Some research pointed me to https://github.com/sstur/react-rte/blob/master/src/RichTextEditor.js#L148

I'm unable to run the library locally, but switching this to `ref={el => this.editor = el}` and then updating the focus method will do the trick.

**Comment by vestimir** [comment]
I've created a PR with the fix – https://github.com/sstur/react-rte/pull/283

**Comment by unCleanCode** [comment]
Still getting this issue when using React.StrictMode

**Comment by solarstar101** [comment]
same bug in 2023
