### ISSUE TITLE
Unable to load soft newlines with createValueFromString

### ISSUE THREAD

**Issue by nbrendler** [sstur/react-rte#29]
I'm having trouble figuring out how to load a soft newline. When I type in the editor:

```
Hi
there
```

It spits out the html `<p>Hi<br/>\nthere</p>`. In my case, I'm exporting this html and saving it in a database. When they come back to the editor, I call `createValueFromString` to repopulate the text but the newline is gone... we get `<p>Hi<br/> there</p>`, instead. The newline is now a space.

I tracked this down to the `collapseWhitespace` function in `draft-js-import-element`. I assume there's a good reason to strip out the whitespace so I'm not sure the best way to go about fixing this is.

You can easily repro the issue by appending this block to `EditorDemo.js`:
```html
<div className="row">
  <RichTextEditor
     value={RichTextEditor.createValueFromString(value.toString(format), format)}
     placeholder="Tell a story"
   />
</div>
```
Then fire up the demo page, and type some text with a soft newline (Shift-Enter) in the top editor.

**Comment by sstur** [comment]
Thanks for reporting this @nbrendler! Seems like a bug. I will look into it.

**Comment by sstur** [comment]
I believe this is fixed in https://github.com/sstur/draft-js-import-element/commit/7c0311e95665aa12bb35f010b858c6a950a2565c. Let me know if the issue still happens on latest. Thanks.

**Comment by nbrendler** [comment]
@sstur works with latest... thanks!
