### ISSUE TITLE
Multi line code snippets?

### ISSUE THREAD

**Issue by alfonsoperez** [sstur/react-rte#3]
Hey, good work on this!.

Are you working on this?

**Comment by sstur** [comment]
Thanks @alfonsoperez. I'm not entirely sure what you mean by multi line code snippets. You can certainly put multiple lines in a code block (shift+enter for a soft break) but are you asking about syntax highlighting for code?

**Comment by alfonsoperez** [comment]
Oh yeah, but when pasting a multi-line code snippet and pressing on `{ }`, it converts it to:

`var javascript;`
`javascript = "example";`

and not to, for example:

```
var javascript;
javascript = "example";
```

Which doesn't work when writing the MarkDown for code blocks, 

hope this helps, and again nice work!

**Comment by sstur** [comment]
Ahh right. `{}` button is working as expected in that case. It might be slightly unclear, but that button is "monospace" inline style (similar to using backticks in markdown). The code block style is in the dropdown.
