### ISSUE TITLE
Doesn't work properly on mobile.

### ISSUE THREAD

**Issue by Stuart88** [sstur/react-rte#309]
Selecting predictive text from mobile keyboard doesn't work, it instead inputs the orignal (wrongly spelled) version of the word.

Also, if I clear all the text from the text editor, it won't let me go back into it. It just sort of breaks.

Works perfectly fine on desktop.

Issues are only on mobile. 

Tested on Chrome and Firefox for Android, using SwiftKey keyboard and default Android keyboard.

**Comment by Stuart88** [comment]
So I've found this: https://github.com/sstur/react-rte/issues/186

Looks like the issue is due to draft.js. The react-rte demo example (https://react-rte.org/demo) suffers the same problem on my phone too.

I presume this is an ongoing and as yet unfixed issue which is down to draft.js, not react-rte..?

**Comment by ScottLindley** [comment]
I believe this is related to https://github.com/sstur/react-rte/issues/257
