### ISSUE TITLE
issue with draft-js-export-html package's dependency draft-js-utils

### ISSUE THREAD

**Issue by prachikarekar** [sstur/react-rte#317]
npm ERR! notarget No compatible version found: draft-js-utils@^1.3.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.3.2, 1.3.0, 1.2.4, 1.2.0, 1.1.0, 1.0.2, 1.0.1, 0.2.0, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'draft-js-export-html'
npm ERR! notarget

**Comment by canpolatoral** [comment]
https://github.com/sstur/draft-js-utils/issues/171
Omg! A huge mistake...

if you add this dependencies in your package.json, it works...

"draft-js-export-html": "1.3.2",
"draft-js-export-markdown": "1.3.2",
"draft-js-import-element": "1.3.2",
"draft-js-import-html": "1.3.2",
"draft-js-import-markdown": "1.3.2",
"draft-js-utils": "1.3.2",

**Comment by sstur** [comment]
This has been fixed. Thanks for bringing it to my attention!
