### ISSUE TITLE
Links are broken when read from string

### ISSUE THREAD

**Issue by srianbury** [sstur/react-rte#323]
When I read an `<a>` tag from string with `RichTextEditor.createValueFromString`, render it to the screen in the RTE Component, then click on it, instead of redirecting to the link it just adds the link to the end of the current pages path.  i.e. 
Page `https://mysite.io/` with a link like `<a href="https://www.google.com">https://www.google.com</a>` will redirect to `https://mysite/"https://"https://"https://www.google.com"`.  Here is an example: https://codesandbox.io/s/rtewonkylinks-73qdk

**Comment by sstur** [comment]
That's because your HTML is not:
```html
<a href="https://www.google.com">https://www.google.com</a>
```
instead, your example has:
```html
<a href=&quot;https://www.google.com&quot;>https://www.google.com</a>
```
which is very different.
If you change it to the first one, the [codesandbox works great](https://codesandbox.io/s/rtewonkylinks-0lk49).
