### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by anowlcalledjosh** [sstur/react-rte#328]
The last release, 0.16.1, is over a year old, and is missing some key features including [the ability to edit links](https://github.com/sstur/react-rte/pull/276).

Are there plans for a new release, or is this project abandoned?

**Comment by dmr** [comment]
What can I do to help?

**Comment by sibelius** [comment]
hey @sstur can you add more contributors so we can upgrade this package?

**Comment by sstur** [comment]
Hey @sibelius, I added you as a contributor. Thanks for the help with this!

**Comment by ivanatworkjam** [comment]
> The last release, 0.16.1, is over a year old, and is missing some key features including [the ability to edit links](https://github.com/sstur/react-rte/pull/276).
> 
> Are there plans for a new release, or is this project abandoned?

Was [the ability to edit links](https://github.com/sstur/react-rte/pull/276) released?
