### ISSUE TITLE
npm run build-demo command not working

### ISSUE THREAD

**Issue by joepsz** [sstur/react-rte#35]
In [this commit](https://github.com/sstur/react-rte/commit/36cbbbbaab4ed340220b867004bb5dd0bd648bbe), the build-demo script was removed from the package.json file. 

Adding the line  `    "build-demo": "webpack",` to the package.json file solved the issue for me. Perhaps the readme should be updated or the script should be added back.

**Comment by sstur** [comment]
`build-demo` was replaced with `build-dist` which should create both `dist/demo.js` and `dist/react-rte.js`. In fact, `npm build` will both generate some `lib/` files and also run `build-dist`.

Does this help?

**Comment by joepsz** [comment]
I assume it does, but the readme still says:
`Clone this project. Run npm install. Run npm run build-demo then point the server of your choice (like serv) to /demo.html.`

**Comment by sstur** [comment]
Oh, good catch! I'll update now.

**Comment by sstur** [comment]
Fixed.
