### ISSUE TITLE
Publish a new version??

### ISSUE THREAD

**Issue by 1yzz** [sstur/react-rte#355]
the latest vesion is 2018. Link editing feature is needed.

**Comment by 1yzz** [comment]
Is this repo maintained?

**Comment by robertjwozniak** [comment]
I just found it, and it looks like a great and simple idea. Is it going to be maintained?

**Comment by sstur** [comment]
No, this project hasn't been actively developed or maintained for some time. Unfortunately I don't have any near-future plans to revive this project either.
