### ISSUE TITLE
Editor not editable

### ISSUE THREAD

**Issue by RainFang** [sstur/react-rte#39]
Hi there,

I'm trying to bring onboard react-rte, but I'm having difficulties. I see the editor perfectly rendered on my screen, but the textbox is not recognizing my inputs. My onChange function is getting triggered, though. Would anyone be able to point out what I did wrong?

My changes are:

1. My component's getInitialState returns:
`format: "markdown",
value: Editor.createEmptyValue()`

2.  An onChange function:
`_onChange: function(value) {
            this.setState({value: value});
}`

3. Rendering it:
`<Editor
                            value={this.state.value}
                            onChange={this._onChange}
                            placeholder="My name is Rain"
/>`

The onChange function is triggering, so it's detecting my text input, but it doesn't display any of my text input. I get the feeling the problem is in my onChange function, but I could use some guidance in how to fix it.

Note - I am not using flow. I see that the demo is, and is importing an EditorValue type, that is used in the demo's onChange function. I'm hoping that isn't necessary.

Thanks!

**Comment by sstur** [comment]
That code looks perfect. There is no need to use Flow. The only thing I can think of is to make sure that `_onChange` is correctly bound to `this`. You might need to do `this._onChange = this._onChange.bind(this);` in your constructor (or use an autobind helper). Another way is to create the onChange handler within your constructor or render method.

If you can post the full code somewhere, like a pastebin or gist, then I'll take a look.

**Comment by RainFang** [comment]
I found the problem. It was with my own code. My old code was blocking render.

Thanks for the help. You've done a FANTASTIC job with the editor!

**Comment by sstur** [comment]
Thanks @RainFang!
