### ISSUE TITLE
distribution build

### ISSUE THREAD

**Issue by simpixelated** [sstur/react-rte#4]
So [I started working on this and managed to get it loaded into my app](https://github.com/sstur/react-rte/compare/master...simpixelated:build-lib-dist), but I keep getting the duplicate versions of React error:
https://github.com/callemall/material-ui/issues/2818
https://gist.github.com/jimfb/4faa6cbfb1ef476bd105

I'm importing it using babel + webpack, so I think it has to do with the way webpack loads dependencies, but I'm not sure. Ideally, it would be great if react-rte had a distribution build available after `npm install react-rte` that includes draft-js, immutable.js, but not react/react-dom.

**Comment by simpixelated** [comment]
So after doing some more investigation. I found the solution: https://gist.github.com/jimfb/4faa6cbfb1ef476bd105#gistcomment-1686426

Still not sure if the problem is in webpack, npm link, or a combination of the two. But by moving react/react-dom to peerDependencies in react-rte and then updating webpack.config with the new resolves, I was able to get this working. It's still very finicky though.

**Comment by sstur** [comment]
Thanks @simpixelated! I know there is not really any guidance about getting this working in a project right now (hence the readme says `Note: this is in early stage development. Do not use yet.`) so I'm impressed you were able to make it happen. I'm looking at your changes and I'll pull in most of these and also make a section in the README describing how to use this editor.

A few comments about your changes:

 - You shouldn't need `transform-flow-strip-types` in your babel config. `babel-preset-react` includes this plugin.
 - I don't suggest checking in the compiled files to git although they should be in the npm package.
 - I think we should move all the dependencies to devDependencies with the exception of react/react-dom which should be peer dependencies

I'll get these changes in master.

Thanks!

**Comment by simpixelated** [comment]
Awesome, thanks for the quick feedback and for mentioning me in your commit/package.json! One other issue I ran into, is that the absolute paths in the CSS imports prevented me from importing them via webpack. I created a pull request which fixes the issue for me: https://github.com/sstur/react-rte/pull/9

**Comment by sstur** [comment]
This should be working now. Let me know if there's any other issues. Thanks.

**Comment by simpixelated** [comment]
0.1.10 works great. Thanks!

**Comment by sstur** [comment]
@simpixelated: I just pushed 0.1.11 which includes CSS Modules (requiring me to change the build system again). Let me know if this breaks anything for you. Thanks!
