### ISSUE TITLE
Popup not showing, Images and link

### ISSUE THREAD

**Issue by chemiadel** [sstur/react-rte#405]
Clicking on image button not opening and autofocusing on editor body
https://codesandbox.io/s/modern-feather-7yd9g?file=/src/editor.js

**Comment by talklikethat** [comment]
Same on image and link buttons
https://codesandbox.io/s/falling-resonance-hr7yv?file=/src/RichText.js

**Comment by naishe** [comment]
@talklikethat -- this is perfect reproduction of my case.

**Comment by lexprom** [comment]
Does **align** work? Doesn't work for me.
The funny thing is everything works fine in demo 👀

**Comment by chemiadel** [comment]
CKEditor was my alternative 
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html

**Comment by sstur** [comment]
Hmm, it's possible the CodeSandbox example is using the latest version and the one at react-rte.org is not. I'd need to verify this theory, but don't have time to look into it at the moment. Please do update this thread with any findings.

Also note: this project is not really actively maintained anymore, so I don't recommend using it in production in it's current state.

**Comment by naishe** [comment]
I really liked the ease of setting this up and the clean interface. It covers 90% of my use cases, so I would love this library to live. I cannot promise anything right away, but I will try to have a look and see if I can add some value.

**Comment by sstur** [comment]
Thanks @naishe for your kind words about this. I'd love to keep it going but it's so outdated right now and has a lot of shortcomings. Also not promises, but there's a chance it comes back to life at some point.

**Comment by iPilotte** [comment]
The difference between CodeSandbox and react-rte.org is React version, it does not support React17 yet.
I've already opened PR here > https://github.com/sstur/react-rte/pull/399
