### ISSUE TITLE
Code and quoted markdown is lost

### ISSUE THREAD

**Issue by tjunnone** [sstur/react-rte#45]
All code and quoted blocks are lost when importing markdown. As an example, in the demo at https://react-rte.org/demo:

- Set the mode radio button to Markdown
- Type some text and mark it as a quote or code in the RTE top editor. MD in bottom textarea looks OK.
- Type anything in the MD textarea, which updates the RTE editor, and all quotes and code blocks are lost (quotes become unstyled text, code block content just plain disappears altogether)

**Comment by sstur** [comment]
Ah, yes, thanks for reminding me about this. I was working on a fix over at the dev branch of [draft-js-import-markdown](https://github.com/sstur/draft-js-import-markdown/tree/dev) which is the module that parses Markdown. The plan is to use [remark](http://remark.js.org/) to handle the parsing which should remove these issues. It's not quite finished yet.

**Comment by sstur** [comment]
I've moved this to https://github.com/sstur/draft-js-import-markdown/issues/1
