### ISSUE TITLE
is height of EDITOR not enough?

### ISSUE THREAD

**Issue by jonirrings** [sstur/react-rte#48]
```
.editor :global(.public-DraftEditor-content) {
  height: 110px;
  overflow: auto;
}
```
as it is **the height**  which is set to 110px, but not min-height, is it too low or not grow-able?
any suggested way to modify this outside your module?
sorry if with bad English grammer.

**Comment by eddanger** [comment]
Yes! I'd like to see either setting the `height` to `auto` or having a `min-height` option. I'm investigating to see if it can be modified outside the component.

**Comment by eddanger** [comment]
@jonirrings I just did a quick fork for the time being to remove the 110px fixed height here: https://github.com/eddanger/react-rte

In `package.json`:

```
"react-rte": "git://github.com/eddanger/react-rte.git"
```

**Comment by sstur** [comment]
Sorry for the silence on this issue. I agree this is a bug and I'm happy to fix it. Standby for a fix.

**Comment by sstur** [comment]
This is now fixed in master. I'll publish to npm shortly (fixing another bug first).

**Comment by eddanger** [comment]
Awesome, thanks!

**Comment by jonirrings** [comment]
@eddanger @sstur thanks!!
