### ISSUE TITLE
Isomorphic Support

### ISSUE THREAD

**Issue by timbofield** [sstur/react-rte#50]
Thanks for writing this.

In an isomorphic app, this library fails when rendering on server with 

```

 	            var $ = window.jQuery || window.Zepto;
	                          ^
                TypeError: Cannot read property 'jQuery' of undefined
```

**Comment by timbofield** [comment]
Just found https://github.com/sstur/react-rte/issues/37

Hmm strange because I can include draft.js fine.

**Comment by ZeroCho** [comment]
As I said in #37 I gave up and decided not to render react-rte in server-side.
If you solve this problem, plz let me know.
Actually it is not react-rte problem, but draft-js'

**Comment by jonirrings** [comment]
@ZeroCho I've endeavoured to integrate, but failed too as the draft-js used ua-parser-js. shall we add an issue to the official draft-js repo?

**Comment by ZeroCho** [comment]
@jonirrings yes, after I search for similar issues in draft-js repo

**Comment by sstur** [comment]
I'm going to close this as I believe this is not possible until draft-js supports it.

**Comment by andrewmclagan** [comment]
an interim solution

````
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';

class MyComponent {
  render() {
    return (
      <div>
        { canUseDOM && React.createElement(require('react-select')) }
      </div>
    );
  }
}
````

**Comment by artskar** [comment]
@andrewmclagan thats is not working. :\

https://github.com/sstur/react-rte/issues/175
