### ISSUE TITLE
Editing a link URL

### ISSUE THREAD

**Issue by gederer** [sstur/react-rte#54]
Is there a way to edit the URL in a link? I think I would expect that when:

1. I position the cursor within an existing link text in the editor (or select an existing link text).
2. I click the link button in the toolbar.

Then 

1. The textbox in the link widget would be populated with the existing link.
2. Editing the contents of the link textbox and clicking the submit button would update the link text.

**Comment by sstur** [comment]
This is an open issue #15 

I intend to get this feature done. Just have not done so yet. Will keep that issue posted with progress.

**Comment by gederer** [comment]
@sstur Grand. Thanks.
