### ISSUE TITLE
nodeName of undefined in IE 11?

### ISSUE THREAD

**Issue by zackify** [sstur/react-rte#56]
<img width="553" alt="screen shot 2016-05-31 at 4 18 53 pm" src="https://cloud.githubusercontent.com/assets/449136/15689105/6475ef0e-274b-11e6-830d-606592244f7e.png">

This happens when loading in the editor. It doesn't show up. Not sure if this is a problem due to draftjs itself or due to react-rte. Only happens on IE 11 like I said. Can't stand IE....

**Comment by zackify** [comment]
Using this on constructionjobs.com and would really love it if I could get some help with making this work in IE 11, if you point me in the right direction I could fix it.

**Comment by sstur** [comment]
Hi @zackify. Sorry for the delay. I think this error is in `draft-js-import-element` which react-rte depends on. I'll see if I can figure out why IE11 is braking there..

**Comment by zackify** [comment]
Awesome I'll check it out too.

**Comment by loverajoel** [comment]
any news about this?

**Comment by zackify** [comment]
So I finally checked this out today. Seems the only problem is an element being passed in as null in IE 11 when there's no value inside of the editor. I made a 1 line pull request that fixes the issue. Hopefully you can merge it and make a new release because I need this fix asap! Thanks for pointing me in the right direction. https://github.com/sstur/draft-js-import-element/pull/14 

There may be a more correct way to fix this, but I don't have time to look over the whole import-element script.

**Comment by sstur** [comment]
Hi @zackify. Sorry for the wait on this. And thanks for your pull request. I'll merge it and publish an update asap.

**Comment by sstur** [comment]
Done.

**Comment by zackify** [comment]
Thanks for doing that so quickly!
