### ISSUE TITLE
Currently unusable with browserify

### ISSUE THREAD

**Issue by cvoege** [sstur/react-rte#63]
It seems that react-rte is 100% reliant on webpack to work, which is a bit unfortunate since a fair number of people use other solutions for bundling.

Here's the stack trace if you try to use it with browserify/babelify

`Error2: Cannot find module '!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./IconButton.css' from '/home/cvoege/mimirhq/lms/node_modules/react-rte/dist'
Finished building JS.
buildJS: 496.802ms
Error2: Cannot find module '!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./ButtonWrap.css' from '/home/cvoege/mimirhq/lms/node_modules/react-rte/dist'
Error2: Cannot find module '!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./Button.css' from '/home/cvoege/mimirhq/lms/node_modules/react-rte/dist'
Error2: Cannot find module '!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./InputPopover.css' from '/home/cvoege/mimirhq/lms/node_modules/react-rte/dist'
Error2: Cannot find module '!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./ButtonGroup.css' from '/home/cvoege/mimirhq/lms/node_modules/react-rte/dist'
Error2: Cannot find module '!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./Dropdown.css' from '/home/cvoege/mimirhq/lms/node_modules/react-rte/dist'
Error2: Cannot find module '!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./EditorToolbar.css' from '/home/cvoege/mimirhq/lms/node_modules/react-rte/dist'
Error2: Cannot find module '!!./../node_modules/raw-loader/index.js!./Draft.global.css' from '/home/cvoege/mimirhq/lms/node_modules/react-rte/dist'
Error2: Cannot find module '!!./../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./RichTextEditor.css' from '/home/cvoege/mimirhq/lms/node_modules/react-rte/dist'`

**Comment by cvoege** [comment]
I see now that this has already been reported with a different title.

**Comment by sstur** [comment]
Hi @cvoege. I'd like to get this fixed. `react-rte` should work fine in your Browersify projects because the npm module for `react-rte` has already been compiled using webpack and should be pure ES5 by the time you insert it into your node_modules. If this is not then we need to fix it. Could you provide some details about how to reproduce this problem. We can continue this discussion on #32 or #55 to keep it all in once place.
