### ISSUE TITLE
readOnly support

### ISSUE THREAD

**Issue by skolmer** [sstur/react-rte#64]
If you set readOnly={true} the text input is disabled, toolbar controls are only styled disabled but still clickable. Best would be to hide toolbar completely if readOnly is set, what do you think?

**Comment by sstur** [comment]
Good catch. I agree we should hide or completely disable the toolbar in this case.

**Comment by sstur** [comment]
I will add one comment here as per #65 that we should alias `readOnly` as `default`.

**Comment by sstur** [comment]
Fixed. Thanks to @ZeroCho.
