### ISSUE TITLE
IndexSizeError

### ISSUE THREAD

**Issue by zackify** [sstur/react-rte#68]
```
Failed to execute 'setStart' on 'Range': The offset 30 is larger than or equal to the node's length (11).
``` 
This happened in Chrome 51. Any ideas?

<img width="966" alt="screen shot 2016-07-01 at 4 50 18 pm" src="https://cloud.githubusercontent.com/assets/449136/16534194/0028095a-3fac-11e6-8af6-c492117da8d7.png">

**Comment by sstur** [comment]
Hmm, I expect this is deep in the inner workings of [DraftJS](http://github.com/facebook/draft-js) or one of its dependencies. Would you be able to track down the ContentState at the time of the error and/or steps to reproduce it?

Side note: Where is that screenshot from? Is it a web-based error logging system?

**Comment by zackify** [comment]
It is from sentry. Sadly I can't get the contents at the time of editing. I
could possibly get what got saved in our backend, but that might not be the
same. I feel rude that I posted this here when I could have realized myself
that it was a draftjs problem. Sorry about that haha

**Comment by jtraub** [comment]
It is a Draft.js issue indeed.

I observe it when I enable Grammarly extension and type a word with mistakes. Grammarly wraps such word into custom tag and this causes multiple errors and weird behaviour.

![image](https://cloud.githubusercontent.com/assets/153191/16540064/dd1d8108-4099-11e6-9e77-68bc2c3eaf58.png)

**Comment by sstur** [comment]
So it appears this is an issue with browser plugins mutating DOM nodes. I really wish they didn't do that! I'm going to close this as not-a-bug-in-this-package. Please open again if need be.
