### ISSUE TITLE
Feature request: text-decoration underline style / <ins> Element

### ISSUE THREAD

**Issue by skolmer** [sstur/react-rte#71]
Please add a button to set underlined text.

**Comment by sstur** [comment]
I had this in the past but I removed it for some reason that I can't remember now. There is some opinion that underline as a style should not be used in documents except for in links. This is because users have been conditioned to expect underlined text to be a link.

I am happy to add this back in ad make it optional. This means we need a prop to customize the toolbar. So this feature request depends on #72.

**Comment by skolmer** [comment]
Sounds reasonable. Underline is a requirement in my current project but I understand that this can lead to bad UX. If you are adding customization features to the toolbar please consider to add className props for toolbar buttons. This will make it easier to change icons or add styling like bootstrap's button styles.

**Comment by Calyhre** [comment]
Actually, this is not removed. If you paste underlined text, it will produce `++text++` in markdown, which does not exists in any markdown syntax.

![sicdk](https://cloud.githubusercontent.com/assets/3692274/16565738/91e7d798-420f-11e6-9eb3-3cc8bb032286.gif)

**Comment by sstur** [comment]
> which does not exists in any markdown syntax.

I wouldn't say **_any_** markdown syntax. There are certainly flavors of markdown that support ++text++ (although I don't have a list off hand). The alternative is adding `<ins>` markup in the markdown which is supported by many more parsers (including github flavored markdown). But I really don't like allowing arbitrary html in markdown.

Anyway, I'm undecided as to what's the right thing to do with pasted styles like this. I suppose there should be an option like `allowNonStandardMarkdownSyntax` or possibly an option for each individual non-standard syntax and if those options are off, then maybe strip foreign styles completely.

Thoughts?

**Comment by Calyhre** [comment]
Yeah, might be a good idea!

The main issue here, is `draft-js` not allowing us to whitelist pasted inline styles.
There is an issue for this https://github.com/facebook/draft-js/issues/166

**Comment by skolmer** [comment]
Fixed in #72
