### ISSUE TITLE
Ability to configure toolbar

### ISSUE THREAD

**Issue by sstur** [sstur/react-rte#72]
The availability, order and grouping of toolbar items should be customizable via prop(s).

**Comment by needcaffeine** [comment]
I'd love to be able to add/remove functionality from the toolbar. Specifically, I want to support subscript and superscript, but not allow for headings/alignment.

**Comment by needcaffeine** [comment]
If you think this is too special of a situation I'm happy to deal with them in a local fork, but I just wanted to mention my real-world use case as you think about this feature. Thanks for this project!

**Comment by sstur** [comment]
This is not too special of a request. It's exactly what you should be able to do with this editor. We can't consider react-rte competitive with the mainstream open source editors without this, so it's a high-pri feature. I intend to work on it soon.

**Comment by jason-uh** [comment]
Until this is fully supported, I'm using a hack:
```
  hideCodeBlockSelection() {
    $("select option[value='code-block']").css('display', 'none');
  }

  hideMonospaceButton() {
    $("button[title='Monospace']").css('display', 'none');
  }

  hideStrikethroughButton() {
    $("button[title='Strikethrough']").css('display', 'none');
  }

  componentDidMount() {
    this.hideCodeBlockSelection();
    this.hideMonospaceButton();
    this.hideStrikethroughButton();  
  }

```

**Comment by edelgado** [comment]
Thanks for the hack. Here is a way to do it without needing jQuery:

```
  hideQuoteButton() {
    let el = document.querySelector("button[title='Blockquote']");
    el.style.cssText = "display: none";

  }
```

**Comment by zackify** [comment]
I'm not that familiar with the codebase, but I need this feature. If you can point me in the right direction I can send a PR that allows customization.

**Comment by martriay** [comment]
Is there anyone working on this? I might implement it and it would be nice for us to work together instead of stepping on our toes.

**Comment by sstur** [comment]
Sorry @martriay, not yet that I know of. I would be open to a PR. I'd like to get this feature in but I am short on time for the near future.

**Comment by skolmer** [comment]
@sstur I have created a PR to add this feature. I have exposed the toolbar config object as RTE prop and added the ability to set custom css classes per toolbar item. hope to get this merged soon :)

**Comment by sstur** [comment]
This is great. Thanks @skolmer!

**Comment by martriay** [comment]
Thanks @skolmer!

**Comment by zackify** [comment]
@sstur I just made a PR for hiding link buttons and the block type dropdowns too. Hope it's good. #108

**Comment by konsalex** [comment]
Hey guys! I was curious how to add a new Button that will have its own logo and when I press it it will add a specific text in the box.

I want to add a Button that when I press it, it will add the text " <LA><LA>" inside the editor's window,
but I cannot seem to understand the Toolbar config.
