### ISSUE TITLE
Provide ability to edit and click on links

### ISSUE THREAD

**Issue by cobarx** [sstur/react-rte#73]
I work with @RainFang and we have been really enjoying using React-RTE as our rich text editor of choice. One of the challenges we've been running into is that we use the editor portion of React-RTE for both editing and viewing text, similar to how Google Docs works. Unlike people who present the HTML output to customers, with only working in editor mode there's no easy way to click on links and open them.

What I'd like to do is create a PR that copies the functionality from Google Docs and make it so that you can edit and click on links inline. The way Google has it setup, the popover shows up whenever the cursor is over the text of the link or when you click on the link, like how it's shown below:
![google docs link](https://cloud.githubusercontent.com/assets/4063255/16634785/233c9038-4384-11e6-8391-3bfb835e80e0.png)
They also have a mode for modifying the link, like this:
![change link](https://cloud.githubusercontent.com/assets/4063255/16634821/58b5ffce-4384-11e6-8b61-438115720cdd.png)

Before I started developing this feature, I wanted to check and see if this is a feature you'd welcome as part of the editor as well as getting a feel for what sort of visual design you'd want. If so, I'd be happy to build it out and submit a PR. 

I've also noticed two other bugs/changes that I'd like to address as part of the same effort if you're ok with this approach:
After creating a link, any additional text you type is included in the link, which makes it hard to enter normal text again. I'd like to copy Docs behavior on this where after you create a link, any text you add reverts back to the default style.
The insert link feature also allows you to insert a link within an existing link, splitting the text into two separate link portions. I'd like to make it so you can only edit an existing link but never add a link in the middle.

Let me know if you'd be ok with this approach for these 3 and I'll get started. Thanks!

**Comment by cobarx** [comment]
@sstur Any chance I could get some feedback on this? I don't want to get started until I'm sure I have the right approach.

**Comment by sstur** [comment]
Hi @cobarx. Sorry about the late reply. I read this last week when you posted it but I have a lot going on and I forgot to reply.

I love this feature suggestion and I'd totally welcome it as part of react-rte!

As for the bugs/changes you propose, I think the first one is great. The second one will change as part of the edit-link feature I'm working on as part of #15 so there will be no more splitting links.

I think this feature suggestion will compliment my work on #15 and they shouldn't conflict with each other.

As for the appearance I think you can use the add link dialog that exists now as a guide, but eventually we should allow the editor to be styled/themed (I'm not sure the best way to approach that. It's another conversation altogether).

Anyway, thanks for opening this issue, feel free to discuss if you run into anything.

Thanks!

**Comment by sstur** [comment]
I will close this for now, but please re-open if you need. Thanks.

**Comment by cobarx** [comment]
That's fine. I have moved to another company, so I won't have a chance to work on this.
