### ISSUE TITLE
IE11: Object doesn't support property or method 'startsWith'

### ISSUE THREAD

**Issue by skolmer** [sstur/react-rte#74]
This error occurs in react-rte.js:6451

```js
	  // check for non-matching names
	  if (!query.startsWith(name)) {
	    return false;
	  }
```

String.prototype.startsWith() is not supported in IE: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

Found this in the docs of draft.js: https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#polyfills

**Comment by jtraub** [comment]
This is not a bug.

If your app will be used in old browsers like IE 11 it is your duty to include appropriate polyfills.

I guess react-rte docs should be updated to indicate the necessity of polyfills.

**Comment by sstur** [comment]
Ah, yes. I think you should pull in [core-js](https://npmjs.com/package/core-js) which will polyfill the necessary ES6 runtime methods. I should make a note about this in the readme.

**Comment by skolmer** [comment]
I could resolve this by adding core-js polyfills. Unfortunately I have still issues in IE11. 
If I call `RichTextEditor.createValueFromString` I get `"Unable to get property 'nodeName' of undefined or null reference"`, any idea what's happening here? 
I checked the draft.js demo in IE11 and everything is working fine. It's hard to say what exactly is causing this issue in react-rte I can only say that the first call to `RichTextEditor.createValueFromString` throws the exception. 
Let me know if I can provide more details or help with testing.

**Comment by skolmer** [comment]
I found the cause of this error. It only occurs in IE11 and only if the value passed to RichTextEditor.createValueFromString() is an empty string. Passing empty strings to createValueFromString is working fine in Chrome and Firefox.

**Comment by sstur** [comment]
@skolmer: Did you find a workaround for `RichTextEditor.createValueFromString('')` on IE11? If so would you let me know what you did? I will create a new issue for this.

**Comment by skolmer** [comment]
@sstur If I remember right the workaround was to use RichTextEditor.createEmptyValue() if the value passed to the RTE is an empty string.
