### ISSUE TITLE
After converting to markdown then convert back by createValueFromString(string,'markdown'), text in Code Block won't show

### ISSUE THREAD

**Issue by binbinfrog** [sstur/react-rte#75]
I want to keep user's input in session storage, so I save user's article by `sessionStorage.setItem(storageName, this.state.value.toString('markdown'))`
but when I reload the cache by 
`ReactRTE.createValueFromString(sessionStorage[storageName], 'markdown')`

text in Code Block just won't show, is there any suggestion?

however, html format is OK

**Comment by sstur** [comment]
Yes, this is a known issues. I was working on a better Markdown implementation over on the dev branch of https://github.com/sstur/draft-js-import-markdown. I will try to get that out at some point in the near future.

**Comment by yfr** [comment]
What's the status here? Would love it to be fixed. Would also help with it.
