### ISSUE TITLE
Update to fix React 15.2 warnings

### ISSUE THREAD

**Issue by zackify** [sstur/react-rte#76]
Some props are being passed to buttons that should not be there. If I have time I'll submit a PR, just wanting to point this out though.
<img width="1248" alt="screen shot 2016-07-11 at 2 11 19 pm" src="https://cloud.githubusercontent.com/assets/449136/16741477/68afa042-4771-11e6-8b53-6bad51a52f46.png">

**Comment by sstur** [comment]
This has already been fixed in https://github.com/sstur/react-rte/pull/70
