### ISSUE TITLE
Editor is can't receive text

### ISSUE THREAD

**Issue by pionl** [sstur/react-rte#78]
Hi,

The editor renders with all settings I provide (value, className, placeholder), unfortunately when I write text, nothing shows (cursor is blinking, onChange event is called).

React version: 15.2.1 (currently stuck on this version, can't downgrade)
Latest chrome
Button are not reacting too, only paragraph select

```javascript
<RichTextEditor value={RichTextEditor.createValueFromString(this.state.note.text, 'markdown')}
                            placeholder="Test"
                            className="editor"
                            editorClassName="editor-view"/>
```

Thank you,
Best regards,
Martin

**Comment by jtraub** [comment]
Could you please create a [MCVE](http://stackoverflow.com/help/mcve)?

**Comment by sstur** [comment]
My guess is that your state is never being updated within the onChange event. Or a re-render is never happening. Or the `value={}` prop  is sending the wrong/empty/initial value.

**Comment by pionl** [comment]
Sure, I'll try to create a sample when there will be a free time.

Let you know. Thanks for the support

**Comment by sstur** [comment]
Without a complete verifiable example, I'm going to close this as "can't repro".

@pionl: if you do come up with a reliable repro, please comment back here. Thanks.

**Comment by pionl** [comment]
@sstur I've updated to latest version and also updated the code to use newly updated readme. Now it works, probably I didn't understand, that I have to update the state value to update the editor (I thought that the editor handles the value state by it self). Thanks for the package!
