### ISSUE TITLE
Allow a custom way to insert the required CSS into the browser

### ISSUE THREAD

**Issue by optimatex** [sstur/react-rte#82]
Rte comes with a bunch of inline styles which make editor looks like in ur demo. How can i manage this styles or disable them?

**Comment by ZeroCho** [comment]
@demoritik 
you can pass **toolbarClassName, editorClassName, customStyleMap** to style.

**Comment by Slapbox** [comment]
Are there any other props that can be passed? I'm trying to style the editor to start with an area of 300x300 pixels and clicking anywhere when it's empty to focus on the editor. Right now though it only expands as needed to fit content.

**Comment by teefan** [comment]
@ZeroCho I passed those className, but it got overridden by the inline styles injected at bottom of HEAD tag.

**Comment by sstur** [comment]
Hi @teefan. I see your problem. I think react-rte should accept a function like `insertCSS` as a prop that would allow you to insert the styles to the document in your own way. That is not something that is immediately on our roadmap but I'd be open to this in the future.

I've updated the title of this issue.

**Comment by louh** [comment]
I'm dealing with this by using `!important` in my CSS declarations to override the inline styles. This isn't ideal, but works a little more cleanly than an arbitrary CSS injection API.

I would prefer some sort of behavior where the inline styles are not applied at all if a `className` is provided, allowing the developer to assume full control of styling. But if the `className` prop is not provided, inline styles could still be applied to facilitate simple drop-in of the component.
