### ISSUE TITLE
Feature request: language attribute for code tag

### ISSUE THREAD

**Issue by ZeroCho** [sstur/react-rte#83]
I know that this is not possible now, but some day it should be made to enable syntax highlighting

**Comment by sstur** [comment]
Hi @ZeroCho. Thanks for opening this issue, I realize it's been a while. I like the idea of syntax-highlighting code blocks in general but this is not currently on my roadmap. I do however have plans to add plugin functionality to https://github.com/sstur/draft-js-import-html and https://github.com/sstur/draft-js-export-html on which this editor is built. That would allow you to implement syntax highlighting using a pre-existing library.

For now I will close this issue.
