### ISSUE TITLE
BLOCK_TYPE_DROPDOWN not rendering options

### ISSUE THREAD

**Issue by ljovanovic** [sstur/react-rte#84]
Hello, I'm working to integrate your component, and for some reason the toolbar is rendering without any options present within the BLOCK_TYPE_DROPDOWN dropdown in the toolbar.  When I inspect the dropdown, it is simply an empty select input, void of any options.

The markup present within the browser is:

`<div class="ButtonGroup__root___3lEAn"><span class="Dropdown__root___3ALmx" title="Normal"><select></select><span class="Dropdown__value___34Py9">Normal</span></span></div>`

Any help you can offer is greatly appreciated.  Thank you.

**Comment by ljovanovic** [comment]
Most recent version of Chrome, 

Version 52.0.2743.82 (64-bit).

The demo loads fine, so there is some conflict occurring within my react project.  I’ve hidden the dropdown until I have more time to debug it, but wanted to reach out in the meantime in the event someone had seen this before or had thoughts as to how the select could render without options.

On Sat, Jul 23, 2016 at 12:33 PM Hyunyoung Cho

<
mailto:Hyunyoung Cho <notifications@github.com>
> wrote:

As an user of this package, I've never experienced that. Which browser do you use?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/sstur/react-rte/issues/84#issuecomment-234730301
, or

**Comment by sstur** [comment]
I have not seen this. There was once an issue with the options being transparent (invisible) in some browser on Windows (I don't remember which one). But that was fixed in react-rte via a CSS update a few versions ago. I'm going to close this as "can't repro" but if you can come up with a reliable repro for this issue, please comment back here. Thanks!
