### ISSUE TITLE
When debugging the source code doesn't match the source file

### ISSUE THREAD

**Issue by ethan-deng** [sstur/react-rte#87]
I added devtool to the webpack.config.js file to get the source map to debug the code.

module.exports = [{
  devtool: '#source-map',

but the source code opened in Chrome debugger doesn't match the file. Is it a problem caused the CSS module file?
![debugwithchrome](https://cloud.githubusercontent.com/assets/11064831/17320580/2a785f2e-5849-11e6-895e-2884adbe16ba.png)

**Comment by sstur** [comment]
Yes, this is possibly related to CSS Modules which will soon be fixed. I will close this issue, please follow #93 for updates.
