### ISSUE TITLE
Handling return presses

### ISSUE THREAD

**Issue by StephenGrider** [sstur/react-rte#90]
It appears that the `handleReturn` prop is overridden by React-rte (see here: https://github.com/sstur/react-rte/blob/master/src/RichTextEditor.js#L85).

My use case for React-rte is in a messaging application where I wish to keep the usual 'submit-on-enter' functionality around, but this prop getting overrode is preventing that behavior.  Is there a workaround to this?

**Comment by sstur** [comment]
I've fixed this by accepting a `handleReturn` prop which will be called first and if it returns true (meaning the keystroke was handled) then our handlers will not run. The update is now in master and I will release a new version to npm soon.
