### ISSUE TITLE
Remove CSS Modules

### ISSUE THREAD

**Issue by sstur** [sstur/react-rte#93]
Use JSS or Aphrodite instead. This will fix a number of issues including server-side rendering, browserify, sourcemap issues, etc.

**Comment by koryteg** [comment]
can you do a patch version bump for this to get it out. ( I tried just using this commit in my package.json but it doesnt seem to work. ) it is not building the dist folder.

**Comment by thebigredgeek** [comment]
https://github.com/markdalgleish/jss-loader < Not sure if this will matter.  JSS-Loader recommends that you use it WITH css-modules lmao

**Comment by sstur** [comment]
Hi @asaf. Not yet. But I will get try to get this done before next week.

**Comment by john-osullivan** [comment]
Hope you're able to get the fix out soon!  This is the best WYSIWIG rich text editor I've found for react, but this issue keeps webpack from being able to build.  I'm not actually doing SSR, but this somehow breaks the chain -- I get this error in the build process: https://github.com/sstur/react-rte/issues/81

**Comment by theguxi** [comment]
Any progress towards SSR compatible?

**Comment by petterrostrup** [comment]
Any progress? Seems like the best editor we can use atm, but the build errors are a bit staggering

**Comment by amygdaloideum** [comment]
Are there any plans of completing this issue anytime soon? Else I must seek other options.

**Comment by CharlesOy** [comment]
I really hope someone fixes this issue.

**Comment by thebigredgeek** [comment]
Yeah I just stopped using React-RTE.  Started using draftjs by itself like 6 months ago, and it's honestly not that bad.

**Comment by qburnsFB** [comment]
If you've hunted around, you probably saw people hint at a workaround for this. I had tried a few of them, but they didn't really give a clear solution. I managed to get React-RTE to work in my universally rendered app. It's totally hacky and I have no promises this will work on your setup, but it's worth a shot:

In your webpack configuration, add a BROWSER env variable like so:
```
BROWSER: JSON.stringify(true)

// my setup as an example
    new webpack.DefinePlugin({
      'process.env': { NODE_ENV: JSON.stringify(nodeEnv), BROWSER: JSON.stringify(true) },
      __CLIENT__: true,
      __SERVER__: false,
      __DEV__: isDev,
    }),
```

Then, wherever you use React-RTE, you want to conditionally import it based on that ENV variable. We can't use ES6 style imports here, but whatever:
```
var RichTextEditor;
if (process.env.BROWSER) { RichTextEditor = require('react-rte').default; }
```

Then finally, use ReactRTE like so:```

render () {
      return (
        <div>
          { RichTextEditor ? <RichTextEditor
            value={this.state.value}
            onChange={this.onChange}
            className={styles.EditorBox}
            autoFocus
          /> : null }
        </div>
     );
}
```


Hope this helps others! React-RTE seems to be way ahead of others, so I didn't want to switch if at all possible.

**Comment by bherila** [comment]
Server side rendering is now supported as of the latest `master` branch :)
@thebigredgeek @qburnsFB  @amygdaloideum  @oychao

**Comment by KeitelDOG** [comment]
2020 and still get the `window not defined` error. Using the solution of @qburnsFB , but without engaging webpack config complexity, I just check if `window` exist so I can render the `RichTextEditor` like this:

```js
const isBrowser = typeof window !== 'undefined';
let RichTextEditor;
if (isBrowser) {
  RichTextEditor = require('react-rte').default;
}
```

And later you can display it with condition in the render section (using Hooks in my case:

```js
{
  RichTextEditor &&
  <RichTextEditor className={classes.richTextEditor}
  value={textEditor} onChange={handleEditorChange}/>
}
```
