### ISSUE TITLE
How to get current cursor position?

### ISSUE THREAD

**Issue by cutbko** [sstur/react-rte#98]
I need to implement functionality like here in github. When user types @ he needs to get dropdown with users. I am able to identify that @ was added but how to get cursor position to render dropdown there?

**Comment by teknologist** [comment]
Hi @cutbko ,

Did you solve this ? I have the exact same functionnality needed. As RTE does not support draftjs plugin i can't use mention plugin.

Any pointers would be very helpful!

Thanks,

Cheers!

E

**Comment by cutbko** [comment]
hi @teknologist 
since reactrte is a wrapper over draftjs and it just renders everything in ContentEditable node you can use default javascript functions to achieve what you need, look for this topic to start from: http://stackoverflow.com/questions/4767848/get-caret-cursor-position-in-contenteditable-area-containing-html-content

**Comment by sstur** [comment]
@teknologist and @cutbko. I do not think it will work if you use normal JS functionality to do this. It is OK (but not ideal) to use normal JS to \*read\* from the document but if you modify the document in any way, React will probably throw some runtime errors. It's highly recommended to use Draft API for this. I do not have an example at this time but you could possibly look at the source code for draftjs-plugins.

**Comment by teknologist** [comment]
@cutbko @sstur  Many thanks for the info guys.
I will have a look at this in the future. Right now we moved to QuillJS and achieved all this very easily.
Thanks again though!

**Comment by sstur** [comment]
Quill is a great editor! It is also well maintained and more mature than Draft/React-RTE. It doesn't always fit perfectly in with a completely React app which is partly why we built this. But I am happy to hear it fits your needs.

**Comment by cutbko** [comment]
@sstur this won't modify the DOM in any way, just will get the cursor position.

**Comment by teknologist** [comment]
Thanks @cutbko will defineltely have a look.

**Comment by teknologist** [comment]
@sstur 

yes? I agree. I wanted a pure react component that would fit our react centric app. that is why we tried RTE. At first I thought I could use the mentions plugin but then figured out I couldn't.

I am using react quill right now which is a nic enough react wrapper around quill... Still has some render issues with the toolbar but at least the mention thing was stratightforward to implement and the API and data model is simpler in my opinion.

Will definetly have keep an eye on React RTE though... ;-)
